"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

type Option={id:string;label:string};
export function FinalizationClient({organizationId,engagementId,status,workpapers,reports,readiness}:{organizationId:string;engagementId:string;status:string;workpapers:Option[];reports:Option[];readiness:{review_ready:boolean;signoff_ready:boolean;report_ready:boolean;closure_ready:boolean;freeze_ready:boolean}}){const router=useRouter();const[msg,setMsg]=useState<string|null>(null);const[busy,setBusy]=useState(false);async function send(action:string,payload:Record<string,unknown>={}){setBusy(true);setMsg(null);const r=await fetch(`/api/organizations/${organizationId}/engagements/${engagementId}/finalization`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,...payload})});const b=await r.json();setBusy(false);if(!r.ok){setMsg(b.message??"Action rejected");return;}setMsg("Saved.");router.refresh();}
 return <section className="workspace-panel"><div className="section-heading"><div><p className="eyebrow">Final assurance actions</p><h2>Review, sign-off, report and freeze</h2></div></div>{msg&&<p className="form-message">{msg}</p>}<div className="organization-grid">
  <article className="organization-card"><h3>Enter review</h3><p>Moves TESTING to REVIEW using the lifecycle trigger.</p><button disabled={busy||status!=="TESTING"} onClick={()=>void send("enter_review")}>Enter REVIEW</button></article>
  <form className="organization-card auth-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void send("review_workpaper",{workpaperId:d.get("workpaperId"),status:d.get("status"),comments:d.get("comments")});}}><h3>Review workpaper</h3><select name="workpaperId" required defaultValue=""><option value="" disabled>Workpaper</option>{workpapers.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select name="status" defaultValue="APPROVED"><option>APPROVED</option><option>REJECTED</option></select><textarea name="comments" placeholder="Review comments"/><button disabled={busy}>Record review</button></form>
  <form className="organization-card auth-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void send("signoff",{statement:d.get("statement")});}}><h3>Human sign-off</h3><textarea name="statement" required placeholder="Sign-off statement"/><button disabled={busy||status!=="REVIEW"||!readiness.review_ready}>Approve sign-off</button></form>
  <form className="organization-card auth-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void send("generate_report",{reportType:"FINAL_ASSURANCE",summary:d.get("summary")});}}><h3>Generate report version</h3><textarea name="summary" placeholder="Executive summary"/><button disabled={busy||status!=="REVIEW"}>Generate report</button></form>
  <form className="organization-card auth-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void send("approve_report",{reportId:d.get("reportId")});}}><h3>Approve latest report</h3><select name="reportId" required defaultValue=""><option value="" disabled>Pending report</option>{reports.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><button disabled={busy}>Approve report</button></form>
  <article className="organization-card"><h3>Close engagement</h3><p>Requires review readiness, approved human sign-off and approved latest report.</p><button disabled={busy||status!=="REVIEW"||!readiness.closure_ready} onClick={()=>void send("close_engagement")}>Close engagement</button></article>
  <form className="organization-card auth-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void send("freeze_engagement",{freezeReason:d.get("freezeReason")});}}><h3>Freeze audit</h3><textarea name="freezeReason" required placeholder="Freeze reason"/><button disabled={busy||status!=="CLOSED"||!readiness.freeze_ready}>Create immutable audit freeze</button></form>
 </div></section>;}
