-- DPM-Assure global abuse-control primitive for authentication-sensitive endpoints.
-- Keys are SHA-256 digests generated by the application; raw email/IP values are never stored here.

CREATE TABLE request_rate_limits (
  rate_key char(64) NOT NULL CHECK (rate_key ~ '^[0-9a-f]{64}$'),
  window_start timestamptz NOT NULL,
  request_count integer NOT NULL CHECK (request_count > 0),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (rate_key, window_start)
);

REVOKE ALL ON request_rate_limits FROM PUBLIC;

CREATE OR REPLACE FUNCTION consume_rate_limit(
  p_rate_key char(64),
  p_max_requests integer,
  p_window_seconds integer
) RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  bucket_start timestamptz;
  new_count integer;
BEGIN
  IF p_rate_key !~ '^[0-9a-f]{64}$' THEN RAISE EXCEPTION 'invalid rate-limit key'; END IF;
  IF p_max_requests <= 0 OR p_window_seconds <= 0 THEN RAISE EXCEPTION 'invalid rate-limit configuration'; END IF;
  bucket_start := to_timestamp(floor(extract(epoch from clock_timestamp()) / p_window_seconds) * p_window_seconds);

  INSERT INTO request_rate_limits(rate_key,window_start,request_count,updated_at)
  VALUES(p_rate_key,bucket_start,1,now())
  ON CONFLICT(rate_key,window_start) DO UPDATE
    SET request_count=request_rate_limits.request_count+1, updated_at=now()
  RETURNING request_count INTO new_count;

  DELETE FROM request_rate_limits
   WHERE rate_key=p_rate_key AND window_start < bucket_start - make_interval(secs => p_window_seconds * 2);

  RETURN new_count <= p_max_requests;
END;
$$;

REVOKE ALL ON FUNCTION consume_rate_limit(char(64),integer,integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION consume_rate_limit(char(64),integer,integer) TO PUBLIC;

COMMENT ON FUNCTION consume_rate_limit(char(64),integer,integer) IS 'Atomic fixed-window rate limit suitable for stateless/serverless application instances. Inputs use one-way hashed identifiers.';
