"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

const tasks=["DOCUMENT_SUMMARY","EVIDENCE_EXTRACTION","FINDING_DRAFT","GAP_ANALYSIS","MAPPING_SUGGESTION","REMEDIATION_SUGGESTION"];
export function AiAssistantClient({organizationId,generations,canReview,canPublish}:{organizationId:string;generations:Array<any>;canReview:boolean;canPublish:boolean}){
 const router=useRouter();const[busy,setBusy]=useState(false);const[msg,setMsg]=useState<string|null>(null);const[latest,setLatest]=useState<Record<string,unknown>|null>(null);
 async function action(action:string,input:Record<string,unknown>){setBusy(true);setMsg(null);const r=await fetch(`/api/organizations/${organizationId}/ai`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,input})});const b=await r.json();setBusy(false);if(!r.ok){setMsg(b.message??"AI action rejected");return null;}router.refresh();return b.result;}
 return <><section className="workspace-panel"><div className="section-heading"><div><p className="eyebrow">AI assistant</p><h2>Source-grounded assistance</h2></div></div><p className="lede compact">AI output is advisory only. It cannot establish compliance truth, approve audit conclusions, sign off an engagement, or bypass an Evidence Gate.</p>{msg&&<p className="form-message">{msg}</p>}<form className="auth-form" onSubmit={async e=>{e.preventDefault();const d=new FormData(e.currentTarget);const refs=String(d.get("sourceReferences")??"").split("\n").map(v=>v.trim()).filter(Boolean);const material=String(d.get("sourceMaterial")??"").split("\n---\n").map(v=>v.trim()).filter(Boolean);const result=await action("generate",{task:d.get("task"),prompt:d.get("prompt"),promptVersion:"DPM-AI-1",sourceReferences:refs,sourceMaterial:material});if(result){setLatest(result.output);setMsg(`Generated as ${result.reviewStatus}. Human review required.`);}}}><select name="task" defaultValue="DOCUMENT_SUMMARY">{tasks.map(t=><option key={t}>{t}</option>)}</select><textarea name="prompt" required placeholder="What should the assistant do?"/><textarea name="sourceReferences" placeholder="Source references, one per line"/><textarea name="sourceMaterial" required placeholder="Source-backed material only. Separate documents with a line containing ---"/><button disabled={busy}>{busy?"Generating…":"Generate assistance"}</button></form>{latest?<pre className="code-block">{JSON.stringify(latest,null,2)}</pre>:null}</section>
 <section className="workspace-panel"><div className="section-heading"><h2>Generation ledger</h2><span className="count-badge">{generations.length}</span></div><div className="signal-list">{generations.map(g=><article className="signal-card" key={g.id}><div className="signal-meta"><span className="role-badge">{g.review_status}</span><span>{g.model_provider} · {g.model_name}</span></div><h3>{g.source_type}</h3><p>Input hash: <code>{g.input_hash}</code></p><pre className="code-block">{JSON.stringify(g.output,null,2)}</pre><div className="card-actions">{canReview&&["AI_REVIEW_PENDING","HUMAN_REVIEW"].includes(g.review_status)?<><button className="secondary-button" disabled={busy} onClick={()=>void action("review",{generationId:g.id,decision:"APPROVED"})}>Approve</button><button className="secondary-button" disabled={busy} onClick={()=>void action("review",{generationId:g.id,decision:"REJECTED"})}>Reject</button></>:null}{canPublish&&g.review_status==="APPROVED"?<button disabled={busy} onClick={()=>void action("publish",{generationId:g.id})}>Publish reviewed output</button>:null}</div></article>)}</div></section></>;
}
