import "server-only";

import { sql } from "drizzle-orm";
import type { AuthorizedTenantTransaction } from "@/auth/authorize";
import { permissions, requirePermission } from "@/auth/rbac";
import { recordDomainChange } from "@/domain/record-event";
import { assertConclusiveTestAllowed, deriveOverallGateResult, validateEvidenceRegistration, type EvidenceGateDimensions, type EvidenceRegistrationInput, type GateResult, type TestResultStatus } from "./validation";

export class EvidenceExecutionError extends Error { constructor(message:string){super(message);this.name="EvidenceExecutionError";} }
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function uuid(v:unknown,n:string){if(typeof v!=="string"||!UUID.test(v))throw new EvidenceExecutionError(`${n} must be a UUID`);return v;}
function text(v:unknown,n:string,max=20000){if(typeof v!=="string"||!v.trim())throw new EvidenceExecutionError(`${n} is required`);const x=v.trim();if(x.length>max)throw new EvidenceExecutionError(`${n} must not exceed ${max} characters`);return x;}
async function requireTesting(tx:AuthorizedTenantTransaction,engagementId:string){const r=await tx.db.execute<{status:string}>(sql`select status::text from engagements where id=${engagementId}::uuid and organization_id=${tx.context.organizationId}::uuid`);if(!r.rows[0])throw new EvidenceExecutionError("Engagement not found");if(r.rows[0].status!=="TESTING")throw new EvidenceExecutionError("Evidence execution is only allowed in TESTING");}

export async function registerEvidence(tx:AuthorizedTenantTransaction,input:EvidenceRegistrationInput){requirePermission(tx.membership.role,permissions.evidenceUpload);const v=validateEvidenceRegistration(input);await requireTesting(tx,v.engagementId);
 const r=await tx.db.execute<{id:string}>(sql`insert into evidence(organization_id,engagement_id,workpaper_id,procedure_id,pbc_request_id,filename,mime_type,size_bytes,storage_key,sha256,original_sha256,uploaded_by,source_description,acquired_at,period_start,period_end,source_type) values(${tx.context.organizationId}::uuid,${v.engagementId}::uuid,${v.workpaperId}::uuid,${v.procedureId??null}::uuid,${v.pbcRequestId??null}::uuid,${v.filename},${v.mimeType},${v.sizeBytes},${v.storageKey},${v.sha256},${v.sha256},${tx.principal.userId}::uuid,${v.sourceDescription},${v.acquiredAt??null}::timestamptz,${v.periodStart??null}::date,${v.periodEnd??null}::date,'UPLOAD') returning id`);const row=r.rows[0];if(!row)throw new EvidenceExecutionError("Evidence registration failed");
 await tx.db.execute(sql`insert into evidence_custody_events(organization_id,engagement_id,evidence_id,event_type,actor_user_id,sha256,notes) values(${tx.context.organizationId}::uuid,${v.engagementId}::uuid,${row.id}::uuid,'REGISTERED',${tx.principal.userId}::uuid,${v.sha256},'Initial evidence registration')`);
 await recordDomainChange(tx,{eventType:"engagement.evidence.registered",aggregateType:"engagement",aggregateId:v.engagementId,action:"engagement.evidence.register",entityType:"evidence",entityId:row.id,payload:{workpaperId:v.workpaperId,procedureId:v.procedureId??null,pbcRequestId:v.pbcRequestId??null},newValues:{filename:v.filename,sha256:v.sha256,sizeBytes:v.sizeBytes}});return row;}

export async function recordCustodyEvent(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.evidenceUpload);const evidenceId=uuid(input.evidenceId,"evidenceId"),eventType=text(input.eventType,"eventType",100),sha256=text(input.sha256,"sha256",64),fromLocation=typeof input.fromLocation==="string"?input.fromLocation.trim()||null:null,toLocation=typeof input.toLocation==="string"?input.toLocation.trim()||null:null,notes=typeof input.notes==="string"?input.notes.trim()||null:null;if(!/^[0-9a-f]{64}$/i.test(sha256))throw new EvidenceExecutionError("sha256 must be a 64-character hexadecimal digest");const e=await tx.db.execute<{engagement_id:string}>(sql`select engagement_id from evidence where id=${evidenceId}::uuid and organization_id=${tx.context.organizationId}::uuid`);const engagementId=e.rows[0]?.engagement_id;if(!engagementId)throw new EvidenceExecutionError("Evidence not found");await requireTesting(tx,engagementId);const r=await tx.db.execute<{id:string}>(sql`insert into evidence_custody_events(organization_id,engagement_id,evidence_id,event_type,actor_user_id,from_location,to_location,sha256,notes) values(${tx.context.organizationId}::uuid,${engagementId}::uuid,${evidenceId}::uuid,${eventType},${tx.principal.userId}::uuid,${fromLocation},${toLocation},${sha256.toLowerCase()},${notes}) returning id`);const row=r.rows[0];if(!row)throw new EvidenceExecutionError("Custody event write failed");await recordDomainChange(tx,{eventType:"engagement.evidence_custody.recorded",aggregateType:"engagement",aggregateId:engagementId,action:"engagement.evidence_custody.record",entityType:"evidence_custody_event",entityId:row.id,payload:{evidenceId,eventType},newValues:{fromLocation,toLocation,sha256:sha256.toLowerCase(),notes}});return {evidenceId,custodyEventId:row.id};}

export async function evaluateEvidenceGate(tx:AuthorizedTenantTransaction,input:{evidenceId:string;procedureId?:string|null;gateVersion:string;dimensions:EvidenceGateDimensions;rationale:string}){requirePermission(tx.membership.role,permissions.workpaperReview);const evidenceId=uuid(input.evidenceId,"evidenceId"),procedureId=input.procedureId?uuid(input.procedureId,"procedureId"):null,gateVersion=text(input.gateVersion,"gateVersion",100),rationale=text(input.rationale,"rationale");const e=await tx.db.execute<{engagement_id:string;sha256:string}>(sql`select engagement_id,sha256 from evidence where id=${evidenceId}::uuid and organization_id=${tx.context.organizationId}::uuid`);const evidence=e.rows[0];if(!evidence)throw new EvidenceExecutionError("Evidence not found");await requireTesting(tx,evidence.engagement_id);const overall=deriveOverallGateResult(input.dimensions);
 const r=await tx.db.execute<{id:string}>(sql`insert into evidence_gate_results(evidence_id,gate_version,identity_status,provenance_status,integrity_status,authorization_status,applicability_status,temporal_status,completeness_status,chain_of_custody_status,overall_result,evaluated_by,rationale,procedure_id,evaluated_sha256) values(${evidenceId}::uuid,${gateVersion},${input.dimensions.identity}::gate_result,${input.dimensions.provenance}::gate_result,${input.dimensions.integrity}::gate_result,${input.dimensions.authorization}::gate_result,${input.dimensions.applicability}::gate_result,${input.dimensions.temporal}::gate_result,${input.dimensions.completeness}::gate_result,${input.dimensions.chainOfCustody}::gate_result,${overall}::gate_result,${tx.principal.userId}::uuid,${rationale},${procedureId}::uuid,${evidence.sha256}) returning id`);const row=r.rows[0];if(!row)throw new EvidenceExecutionError("Evidence gate evaluation failed");await recordDomainChange(tx,{eventType:"engagement.evidence_gate.evaluated",aggregateType:"engagement",aggregateId:evidence.engagement_id,action:"engagement.evidence_gate.evaluate",entityType:"evidence_gate_result",entityId:row.id,payload:{evidenceId,procedureId},newValues:{overallResult:overall,gateVersion}});return {...row,overall};}

export async function recordTestResult(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.workpaperUpdate);const workpaperId=uuid(input.workpaperId,"workpaperId"),procedureId=uuid(input.procedureId,"procedureId");const result=text(input.result,"result",30) as TestResultStatus;if(!["PASS","FAIL","INSUFFICIENT_EVIDENCE","NOT_APPLICABLE"].includes(result))throw new EvidenceExecutionError("Invalid test result");const gateId=input.evidenceGateResultId?uuid(input.evidenceGateResultId,"evidenceGateResultId"):null;const w=await tx.db.execute<{engagement_id:string}>(sql`select engagement_id from workpapers where id=${workpaperId}::uuid and organization_id=${tx.context.organizationId}::uuid`);const engagementId=w.rows[0]?.engagement_id;if(!engagementId)throw new EvidenceExecutionError("Workpaper not found");await requireTesting(tx,engagementId);let gate:GateResult|null=null;if(gateId){const g=await tx.db.execute<{overall_result:GateResult}>(sql`select overall_result::text as overall_result from evidence_gate_results where id=${gateId}::uuid`);gate=g.rows[0]?.overall_result??null;}assertConclusiveTestAllowed(result,gate);const conclusion=typeof input.conclusion==="string"&&input.conclusion.trim()?input.conclusion.trim():null;const exceptionSummary=typeof input.exceptionSummary==="string"&&input.exceptionSummary.trim()?input.exceptionSummary.trim():null;const r=await tx.db.execute<{id:string}>(sql`insert into test_results(workpaper_id,procedure_id,evidence_gate_result_id,result,exception_summary,conclusion,tested_by) values(${workpaperId}::uuid,${procedureId}::uuid,${gateId}::uuid,${result}::test_result_status,${exceptionSummary},${conclusion},${tx.principal.userId}::uuid) returning id`);const row=r.rows[0];if(!row)throw new EvidenceExecutionError("Test result write failed");await recordDomainChange(tx,{eventType:"engagement.test_result.recorded",aggregateType:"engagement",aggregateId:engagementId,action:"engagement.test_result.record",entityType:"test_result",entityId:row.id,payload:{workpaperId,procedureId,gateId},newValues:{result,conclusion}});return row;}
