import "server-only";

import { createHash } from "node:crypto";
import { sql } from "drizzle-orm";
import type { AuthorizedTenantTransaction } from "@/auth/authorize";
import { permissions, requirePermission } from "@/auth/rbac";
import { getAiProvider } from "@/ai/groq";
import { assertSupportedAiTask } from "@/ai/provider";
import { recordDomainChange } from "@/domain/record-event";

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const SYSTEM_PROMPT=`You are an assistant inside DPM-Assure, an evidence-driven privacy audit platform. You are NOT an authoritative legal source and you cannot make audit sign-off or compliance certification decisions. Use only the source material supplied in the request. Never invent legal requirements, evidence, citations, facts, test results, or control mappings. If the supplied material cannot support the requested output, set evidence_status to INSUFFICIENT_EVIDENCE and explain what is missing. Distinguish source-backed facts from inference. Return JSON only with keys: evidence_status (SOURCE_BACKED | INFERENCE | INSUFFICIENT_EVIDENCE), summary, facts, inferences, missing_evidence, suggested_next_steps, confidence. A human must review all output before publication.`;
function required(value:unknown,name:string,max:number){if(typeof value!=="string"||!value.trim())throw new Error(`${name} is required`);const v=value.trim();if(v.length>max)throw new Error(`${name} must not exceed ${max} characters`);return v;}

export async function generateAiAssistance(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){
 requirePermission(tx.membership.role,permissions.aiUse);const task=required(input.task,"task",100);assertSupportedAiTask(task);const prompt=required(input.prompt,"prompt",50_000);const promptVersion=required(input.promptVersion??"DPM-AI-1","promptVersion",100);const engagementId=input.engagementId?required(input.engagementId,"engagementId",36):null;if(engagementId&&!UUID.test(engagementId))throw new Error("engagementId must be a UUID");
 const sourceReferences=Array.isArray(input.sourceReferences)?input.sourceReferences.filter((v):v is string=>typeof v==="string"&&v.trim().length>0).map(v=>v.trim()).slice(0,50):[];const sourceMaterial=Array.isArray(input.sourceMaterial)?input.sourceMaterial.filter((v):v is string=>typeof v==="string"&&v.trim().length>0).map(v=>v.trim()).slice(0,100):[];
 const inputEnvelope={task,prompt,promptVersion,sourceReferences,sourceMaterial};const inputHash=createHash("sha256").update(JSON.stringify(inputEnvelope)).digest("hex");
 const generation=await getAiProvider().generate({task,systemPrompt:SYSTEM_PROMPT,userPrompt:`Task: ${task}\nRequest: ${prompt}\nSource references: ${JSON.stringify(sourceReferences)}\nSource material:\n${sourceMaterial.join("\n---\n")}`,sourceReferences});
 const status=generation.output.evidence_status;if(!["SOURCE_BACKED","INFERENCE","INSUFFICIENT_EVIDENCE"].includes(String(status)))throw new Error("AI output omitted required evidence_status");
 const row=(await tx.db.execute<{id:string}>(sql`insert into ai_generations(organization_id,engagement_id,source_type,source_reference,prompt_version,model_provider,model_name,model_version,input_hash,output,confidence,review_status,created_by) values(${tx.context.organizationId}::uuid,${engagementId}::uuid,${task},${JSON.stringify(sourceReferences)},${promptVersion},${generation.provider},${generation.model},${generation.modelVersion??null},${inputHash},${JSON.stringify(generation.output)}::jsonb,${generation.confidence??null},'AI_REVIEW_PENDING',${tx.principal.userId}::uuid) returning id`)).rows[0];if(!row)throw new Error("AI generation could not be recorded");
 await recordDomainChange(tx,{eventType:"ai.generation.created",aggregateType:"ai_generation",aggregateId:row.id,action:"ai.generate",entityType:"ai_generation",entityId:row.id,payload:{task,engagementId,sourceReferences},newValues:{provider:generation.provider,model:generation.model,inputHash,reviewStatus:"AI_REVIEW_PENDING",evidenceStatus:status}});return {id:row.id,reviewStatus:"AI_REVIEW_PENDING",output:generation.output,confidence:generation.confidence??null};
}

export async function reviewAiGeneration(tx:AuthorizedTenantTransaction,input:{generationId:string;decision:"APPROVED"|"REJECTED"}){requirePermission(tx.membership.role,permissions.aiReview);if(!UUID.test(input.generationId))throw new Error("generationId must be a UUID");if(!["APPROVED","REJECTED"].includes(input.decision))throw new Error("Invalid AI review decision");const existing=(await tx.db.execute<{created_by:string;review_status:string}>(sql`select created_by,review_status::text from ai_generations where id=${input.generationId}::uuid and organization_id=${tx.context.organizationId}::uuid for update`)).rows[0];if(!existing)throw new Error("AI generation not found");if(existing.created_by===tx.principal.userId)throw new Error("AI generation creator cannot independently review the same generation");if(!["AI_REVIEW_PENDING","HUMAN_REVIEW"].includes(existing.review_status))throw new Error(`AI generation cannot be reviewed from ${existing.review_status}`);await tx.db.execute(sql`update ai_generations set review_status=${input.decision}::ai_review_status,reviewed_by=${tx.principal.userId}::uuid,reviewed_at=now() where id=${input.generationId}::uuid`);await recordDomainChange(tx,{eventType:"ai.generation.reviewed",aggregateType:"ai_generation",aggregateId:input.generationId,action:"ai.review",entityType:"ai_generation",entityId:input.generationId,payload:{decision:input.decision},newValues:{reviewStatus:input.decision,reviewedBy:tx.principal.userId}});return {id:input.generationId,status:input.decision};}

export async function publishAiGeneration(tx:AuthorizedTenantTransaction,generationId:string){requirePermission(tx.membership.role,permissions.aiPublish);if(!UUID.test(generationId))throw new Error("generationId must be a UUID");const row=(await tx.db.execute<{review_status:string}>(sql`select review_status::text from ai_generations where id=${generationId}::uuid and organization_id=${tx.context.organizationId}::uuid for update`)).rows[0];if(!row)throw new Error("AI generation not found");if(row.review_status!=="APPROVED")throw new Error("Only human-approved AI output may be published");await tx.db.execute(sql`update ai_generations set review_status='PUBLISHED' where id=${generationId}::uuid`);await recordDomainChange(tx,{eventType:"ai.generation.published",aggregateType:"ai_generation",aggregateId:generationId,action:"ai.publish",entityType:"ai_generation",entityId:generationId,payload:{},newValues:{reviewStatus:"PUBLISHED"}});return {id:generationId,status:"PUBLISHED"};}

export async function listAiGenerations(tx:AuthorizedTenantTransaction,engagementId?:string|null){requirePermission(tx.membership.role,permissions.aiUse);const result=engagementId?await tx.db.execute(sql`select id,source_type,prompt_version,model_provider,model_name,input_hash,output,confidence::text,review_status::text,created_by,created_at::text,reviewed_by,reviewed_at::text from ai_generations where organization_id=${tx.context.organizationId}::uuid and engagement_id=${engagementId}::uuid order by created_at desc limit 50`):await tx.db.execute(sql`select id,source_type,prompt_version,model_provider,model_name,input_hash,output,confidence::text,review_status::text,created_by,created_at::text,reviewed_by,reviewed_at::text from ai_generations where organization_id=${tx.context.organizationId}::uuid order by created_at desc limit 50`);return result.rows;}
