import Link from "next/link";
import { redirect } from "next/navigation";
import { sql } from "drizzle-orm";
import { getCurrentUserContext } from "@/auth/current-user-context";
import { withAuthorizedTenantTransaction } from "@/auth/authorize";
import { permissions } from "@/auth/rbac";
import { PrivacyOperationsClient } from "./PrivacyOperationsClient";

export const dynamic="force-dynamic";
type PageProps={params:Promise<{organizationId:string}>};
export default async function PrivacyOperationsPage({params}:PageProps){const{organizationId}=await params;const current=await getCurrentUserContext();if(!current)redirect("/login");const membership=current.memberships.find(x=>x.organizationId===organizationId);if(!membership)redirect("/dashboard");const s=await withAuthorizedTenantTransaction({principal:current.principal,organizationId,requestId:crypto.randomUUID(),permission:permissions.privacyRead},async(tx)=>{
 const activities=(await tx.db.execute<{id:string;name:string;state:string;controller_processor_role:string;next_review_at:string|null}>(sql`select id,name,state::text,controller_processor_role,next_review_at::text from processing_activities where organization_id=${organizationId}::uuid order by name`)).rows;
 const dpias=(await tx.db.execute<{id:string;processing_activity_id:string;version:number;decision:string;created_at:string}>(sql`select id,processing_activity_id,version,decision::text,created_at::text from dpia_assessments where organization_id=${organizationId}::uuid order by created_at desc`)).rows;
 const processors=(await tx.db.execute<{id:string;name:string;status:string;country:string|null;next_review_at:string|null}>(sql`select id,name,status::text,country,next_review_at::text from processors where organization_id=${organizationId}::uuid order by name`)).rows;
 const transfers=(await tx.db.execute<{id:string;processing_activity_id:string;destination_country:string;mechanism:string;state:string;next_review_at:string|null}>(sql`select id,processing_activity_id,destination_country,mechanism::text,state::text,next_review_at::text from international_transfers where organization_id=${organizationId}::uuid order by created_at desc`)).rows;
 const dsrs=(await tx.db.execute<{id:string;request_type:string;status:string;received_at:string;due_at:string|null}>(sql`select id,request_type,status::text,received_at::text,due_at::text from data_subject_requests where organization_id=${organizationId}::uuid order by received_at desc`)).rows;
 const breaches=(await tx.db.execute<{id:string;title:string;status:string;detected_at:string;notification_required:boolean|null;notification_due_at:string|null}>(sql`select id,title,status::text,detected_at::text,notification_required,notification_due_at::text from privacy_breaches where organization_id=${organizationId}::uuid order by detected_at desc`)).rows;
 const alerts=(await tx.db.execute<{id:string;alert_type:string;status:string;due_at:string|null;summary:string}>(sql`select id,alert_type,status::text,due_at::text,summary from privacy_alerts where organization_id=${organizationId}::uuid and status<>'RESOLVED' order by due_at nulls last,created_at desc`)).rows;
 return{activities,dpias,processors,transfers,dsrs,breaches,alerts};});
 return <main className="dashboard-shell"><Link className="back-link" href="/dashboard">← Dashboard</Link><header className="dashboard-header"><div><p className="eyebrow">Privacy operations</p><h1>Operational privacy register</h1><p className="lede compact">RoPA, DPIA, processors, transfers, DSRs and incidents remain operational records—not audit conclusions.</p></div><span className="role-badge">{membership.role.replaceAll("_"," ")}</span></header><section className="monitoring-summary"><article><strong>{s.activities.length}</strong><span>Processing activities</span></article><article><strong>{s.dpias.filter(x=>x.decision!=="APPROVED"&&x.decision!=="NOT_REQUIRED").length}</strong><span>Open DPIAs</span></article><article><strong>{s.dsrs.filter(x=>!['COMPLETED','REJECTED','CANCELLED'].includes(x.status)).length}</strong><span>Open DSRs</span></article><article><strong>{s.alerts.length}</strong><span>Active alerts</span></article></section><PrivacyOperationsClient organizationId={organizationId} activities={s.activities.map(x=>({id:x.id,label:`${x.state} · ${x.name}`}))} dpias={s.dpias.map(x=>({id:x.id,label:`${x.decision} · v${x.version} · ${s.activities.find(a=>a.id===x.processing_activity_id)?.name??"Activity"}`}))} processors={s.processors.map(x=>({id:x.id,label:`${x.status} · ${x.name}`}))} transfers={s.transfers.map(x=>({id:x.id,label:`${x.state} · ${x.destination_country} · ${x.mechanism}`}))} dsrs={s.dsrs.map(x=>({id:x.id,label:`${x.status} · ${x.request_type} · ${new Date(x.received_at).toLocaleDateString()}`}))} breaches={s.breaches.map(x=>({id:x.id,label:`${x.status} · ${x.title}`}))}/><section className="workspace-panel"><div className="section-heading"><h2>Operational status</h2></div><div className="organization-grid"><article className="organization-card"><h3>RoPA</h3><p>{s.activities.filter(x=>x.state==="ACTIVE").length} active / {s.activities.length} total</p></article><article className="organization-card"><h3>Processors</h3><p>{s.processors.filter(x=>x.status==="ACTIVE").length} active / {s.processors.length} total</p></article><article className="organization-card"><h3>Transfers</h3><p>{s.transfers.filter(x=>x.state==="ACTIVE").length} active / {s.transfers.length} total</p></article><article className="organization-card"><h3>Privacy breaches</h3><p>{s.breaches.filter(x=>x.status!=="CLOSED").length} open</p></article></div></section><section className="workspace-panel"><div className="section-heading"><h2>Active privacy alerts</h2></div><div className="signal-list">{s.alerts.map(a=><article className="signal-card" key={a.id}><div className="signal-meta"><span>{a.alert_type}</span><span>{a.due_at?new Date(a.due_at).toLocaleString():"No due date"}</span></div><p>{a.summary}</p></article>)}</div></section></main>;}
