"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

type Choice={id:string;label:string};
export function OutcomeClient({organizationId,engagementId,testResults,findings,evidence}:{organizationId:string;engagementId:string;testResults:Choice[];findings:Choice[];evidence:Choice[]}){const router=useRouter();const[msg,setMsg]=useState("");const[busy,setBusy]=useState(false);async function send(action:string,input:Record<string,unknown>){setBusy(true);setMsg("");const r=await fetch(`/api/organizations/${organizationId}/engagements/${engagementId}/findings`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,...input})});const b=await r.json();setBusy(false);if(!r.ok){setMsg(b.message??"Action rejected");return;}setMsg("Saved");router.refresh();}
 return <section className="workspace-panel"><div className="section-heading"><div><p className="eyebrow">Assurance outcomes</p><h2>Finding lifecycle actions</h2></div></div><div className="organization-grid">
 <form className="auth-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void send("create_exception",{workpaperId:d.get("workpaperId"),testResultId:d.get("testResultId"),description:d.get("description"),severity:d.get("severity")});}}><h3>Create exception</h3><select name="testResultId" required><option value="">Failed test result</option>{testResults.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><input name="workpaperId" placeholder="Workpaper UUID" required/><input name="severity" placeholder="Severity" required/><textarea name="description" placeholder="Exception description" required/><button disabled={busy}>Create exception</button></form>
 <form className="auth-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void send("assess_risk",{findingId:d.get("findingId"),likelihood:Number(d.get("likelihood")),impact:Number(d.get("impact")),methodVersion:"DPM-RISK-MULTIPLICATIVE-1",rationale:d.get("rationale")});}}><h3>Assess finding risk</h3><select name="findingId" required><option value="">Finding</option>{findings.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><input name="likelihood" type="number" min="0" max="5" step="0.01" placeholder="Likelihood 0–5" required/><input name="impact" type="number" min="0" max="5" step="0.01" placeholder="Impact 0–5" required/><textarea name="rationale" placeholder="Risk rationale" required/><button disabled={busy}>Assess risk</button></form>
 <form className="auth-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void send("create_remediation",{findingId:d.get("findingId"),plan:d.get("plan"),targetDate:d.get("targetDate")||null});}}><h3>Plan remediation</h3><select name="findingId" required><option value="">Finding</option>{findings.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><textarea name="plan" placeholder="Remediation plan" required/><input name="targetDate" type="date"/><button disabled={busy}>Create remediation</button></form>
 <form className="auth-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void send("create_retest",{findingId:d.get("findingId"),remediationId:d.get("remediationId")||null,evidenceId:d.get("evidenceId")||null,result:d.get("result"),conclusion:d.get("conclusion")});}}><h3>Record retest</h3><select name="findingId" required><option value="">Finding</option>{findings.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><input name="remediationId" placeholder="Remediation UUID"/><select name="evidenceId"><option value="">Evidence (required for PASS/FAIL)</option>{evidence.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select name="result" required><option>PASS</option><option>FAIL</option><option>INSUFFICIENT_EVIDENCE</option><option>NOT_APPLICABLE</option></select><textarea name="conclusion" placeholder="Retest conclusion" required/><button disabled={busy}>Record retest</button></form>
 </div>{msg&&<p className="form-message">{msg}</p>}</section>}
