"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

type Option={id:string;label:string};
export function OutcomesClient({organizationId,engagementId,testResults,sources,findings,evidence,remediations,pendingRemediations,riskAcceptances}:{organizationId:string;engagementId:string;testResults:Option[];sources:Option[];findings:Option[];evidence:Option[];remediations:Option[];pendingRemediations:Option[];riskAcceptances:Option[]}){
 const router=useRouter();const[msg,setMsg]=useState<string|null>(null);const[busy,setBusy]=useState(false);
 async function send(action:string,payload:Record<string,unknown>){setBusy(true);setMsg(null);const r=await fetch(`/api/organizations/${organizationId}/engagements/${engagementId}/outcomes`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,...payload})});const b=await r.json();setBusy(false);if(!r.ok){setMsg(b.message??"Action rejected");return;}setMsg("Saved.");router.refresh();}
 function form(handler:(d:FormData)=>Record<string,unknown>,children:React.ReactNode,label:string){return <form className="auth-form" onSubmit={e=>{e.preventDefault();void send(String((e.currentTarget.elements.namedItem("action") as HTMLInputElement).value),handler(new FormData(e.currentTarget)));}}><input type="hidden" name="action" value={label.split("|")[0]}/>{children}<button disabled={busy}>{label.split("|")[1]}</button></form>}
 return <section className="workspace-panel"><div className="section-heading"><div><p className="eyebrow">Outcome actions</p><h2>Exceptions, findings and closure</h2></div></div>{msg&&<p className="form-message">{msg}</p>}<div className="organization-grid">
 {form(d=>({testResultId:d.get("testResultId"),description:d.get("description"),severity:d.get("severity")}),<><h3>Create exception</h3><select name="testResultId" required defaultValue=""><option value="" disabled>Failed test result</option>{testResults.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><textarea name="description" placeholder="Exception description" required/><input name="severity" placeholder="Severity" required/></>,"create_exception|Create exception")}
 {form(d=>({testResultId:d.get("testResultId"),observationType:d.get("observationType"),description:d.get("description"),significance:d.get("significance")}),<><h3>Create observation</h3><select name="testResultId" required defaultValue=""><option value="" disabled>Test result</option>{testResults.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select name="observationType" defaultValue="NOTE"><option>NOTE</option><option>IMPROVEMENT_OPPORTUNITY</option><option>CONTROL_DEFICIENCY</option></select><textarea name="description" required placeholder="Observation"/><input name="significance" placeholder="Significance"/></>,"create_observation|Create observation")}
 {form(d=>({sourceType:String(d.get("sourceId")??"").startsWith("EX:")?"EXCEPTION":"OBSERVATION",sourceId:String(d.get("sourceId")??"").slice(3),title:d.get("title"),description:d.get("description"),findingType:d.get("findingType")}),<><h3>Formalize finding</h3><select name="sourceId" required defaultValue=""><option value="" disabled>Assurance source</option>{sources.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><input name="title" placeholder="Finding title" required/><textarea name="description" placeholder="Finding description" required/><input name="findingType" placeholder="Finding type" required/></>,"create_finding|Create finding")}
 {form(d=>({findingId:d.get("findingId"),likelihood:d.get("likelihood"),impact:d.get("impact"),rationale:d.get("rationale"),methodVersion:"DPM-RISK-MULTIPLICATIVE-1"}),<><h3>Assess risk</h3><select name="findingId" required defaultValue=""><option value="" disabled>Finding</option>{findings.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><input name="likelihood" type="number" min="0" max="5" step="0.01" required placeholder="Likelihood 0-5"/><input name="impact" type="number" min="0" max="5" step="0.01" required placeholder="Impact 0-5"/><textarea name="rationale" required placeholder="Risk rationale"/></>,"assess_risk|Assess risk")}
 {form(d=>({findingId:d.get("findingId"),plan:d.get("plan"),targetDate:d.get("targetDate")}),<><h3>Create remediation</h3><select name="findingId" required defaultValue=""><option value="" disabled>Finding</option>{findings.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><textarea name="plan" required placeholder="Remediation plan"/><input name="targetDate" type="date"/></>,"create_remediation|Create remediation")}
 {pendingRemediations.length?form(d=>({remediationId:d.get("remediationId")}),<><h3>Complete remediation</h3><select name="remediationId" required defaultValue=""><option value="" disabled>Active remediation</option>{pendingRemediations.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><p className="lede compact">Completion is recorded before independent retesting and finding closure.</p></>,"complete_remediation|Complete remediation"):null}
 {form(d=>({findingId:d.get("findingId"),rationale:d.get("rationale"),reviewDueAt:d.get("reviewDueAt"),expiresAt:d.get("expiresAt")}),<><h3>Propose risk acceptance</h3><select name="findingId" required defaultValue=""><option value="" disabled>Finding</option>{findings.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><textarea name="rationale" required placeholder="Acceptance rationale"/><label>Review due<input name="reviewDueAt" type="datetime-local" required/></label><label>Expires<input name="expiresAt" type="datetime-local" required/></label></>,"create_risk_acceptance|Create risk acceptance")}
 {form(d=>({findingId:d.get("findingId"),remediationId:d.get("remediationId")||null,evidenceId:d.get("evidenceId")||null,result:d.get("result"),conclusion:d.get("conclusion")}),<><h3>Record retest</h3><select name="findingId" required defaultValue=""><option value="" disabled>Finding</option>{findings.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select name="remediationId" defaultValue=""><option value="">No remediation</option>{remediations.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select name="evidenceId" defaultValue=""><option value="">No evidence</option>{evidence.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select name="result" defaultValue="INSUFFICIENT_EVIDENCE"><option>PASS</option><option>FAIL</option><option>INSUFFICIENT_EVIDENCE</option><option>NOT_APPLICABLE</option></select><textarea name="conclusion" required placeholder="Retest conclusion"/></>,"record_retest|Record retest")}
 {form(d=>({riskAcceptanceId:d.get("riskAcceptanceId")}),<><h3>Approve risk acceptance</h3><select name="riskAcceptanceId" required defaultValue=""><option value="" disabled>Pending acceptance</option>{riskAcceptances.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></>,"approve_risk_acceptance|Approve acceptance")}
 {form(d=>({findingId:d.get("findingId")}),<><h3>Close finding</h3><select name="findingId" required defaultValue=""><option value="" disabled>Finding</option>{findings.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><p className="lede compact">Database closure gate requires verified remediation or a current approved risk acceptance.</p></>,"close_finding|Close finding")}
 </div></section>;
}
