import Link from "next/link";
import { redirect } from "next/navigation";
import { sql } from "drizzle-orm";
import { getCurrentUserContext } from "@/auth/current-user-context";
import { withAuthorizedTenantTransaction } from "@/auth/authorize";
import { permissions } from "@/auth/rbac";
import { OutcomesClient } from "./OutcomesClient";

export const dynamic="force-dynamic";
type PageProps={params:Promise<{organizationId:string;engagementId:string}>};
export default async function OutcomesPage({params}:PageProps){const{organizationId,engagementId}=await params;const current=await getCurrentUserContext();if(!current)redirect("/login");if(!current.memberships.some(x=>x.organizationId===organizationId))redirect("/dashboard");const s=await withAuthorizedTenantTransaction({principal:current.principal,organizationId,requestId:crypto.randomUUID(),permission:permissions.findingRead},async(tx)=>{
 const engagement=(await tx.db.execute<{name:string;status:string}>(sql`select name,status::text from engagements where id=${engagementId}::uuid and organization_id=${organizationId}::uuid`)).rows[0];if(!engagement)throw new Error("Engagement not found");
 const tests=(await tx.db.execute<{id:string;result:string;workpaper_title:string;procedure_name:string}>(sql`select tr.id,tr.result::text,w.title workpaper_title,p.name procedure_name from test_results tr join workpapers w on w.id=tr.workpaper_id join procedures p on p.id=tr.procedure_id where w.engagement_id=${engagementId}::uuid order by tr.tested_at desc`)).rows;
 const exceptions=(await tx.db.execute<{id:string;description:string;severity:string;status:string}>(sql`select id,description,severity,status::text from exceptions where engagement_id=${engagementId}::uuid order by created_at desc`)).rows;
 const observations=(await tx.db.execute<{id:string;description:string;observation_type:string;status:string}>(sql`select id,description,observation_type::text,status::text from observations where engagement_id=${engagementId}::uuid order by created_at desc`)).rows;
 const findings=(await tx.db.execute<{id:string;title:string;status:string;finding_type:string}>(sql`select id,title,status::text,finding_type from findings where engagement_id=${engagementId}::uuid order by created_at desc`)).rows;
 const risks=(await tx.db.execute<{id:string;finding_id:string;score:string;method_version:string}>(sql`select id,finding_id,score::text,method_version from risks where engagement_id=${engagementId}::uuid order by assessed_at desc`)).rows;
 const remediations=(await tx.db.execute<{id:string;finding_id:string;status:string;plan:string}>(sql`select id,finding_id,status::text,plan from remediations where engagement_id=${engagementId}::uuid order by created_at desc`)).rows;
 const acceptances=(await tx.db.execute<{id:string;finding_id:string;approval_status:string;expires_at:string}>(sql`select id,finding_id,approval_status::text,expires_at::text from risk_acceptances where engagement_id=${engagementId}::uuid order by accepted_at desc`)).rows;
 const retests=(await tx.db.execute<{id:string;finding_id:string;result:string;conclusion:string}>(sql`select id,finding_id,result::text,conclusion from retests where engagement_id=${engagementId}::uuid order by tested_at desc`)).rows;
 const evidence=(await tx.db.execute<{id:string;filename:string}>(sql`select id,filename from evidence where engagement_id=${engagementId}::uuid order by uploaded_at desc`)).rows;
 return{engagement,tests,exceptions,observations,findings,risks,remediations,acceptances,retests,evidence};});
 const sourceOptions=[...s.exceptions.map(x=>({id:`EX:${x.id}`,label:`Exception — ${x.description.slice(0,80)}`})),...s.observations.map(x=>({id:`OB:${x.id}`,label:`Observation — ${x.description.slice(0,80)}`}))];const findingOptions=s.findings.filter(x=>x.status!=="CLOSED").map(x=>({id:x.id,label:x.title}));
 return <main className="dashboard-shell"><Link className="back-link" href={`/organizations/${organizationId}/engagements/${engagementId}/execution`}>← Execution</Link><header className="dashboard-header"><div><p className="eyebrow">Assurance outcomes</p><h1>{s.engagement.name}</h1><p className="lede compact">Exceptions, observations, findings, deterministic risk and closure evidence.</p><div className="header-meta"><Link className="secondary-link" href={`/organizations/${organizationId}/engagements/${engagementId}/finalization`}>Final assurance</Link></div></div><span className="role-badge">{s.engagement.status}</span></header><section className="monitoring-summary"><article><strong>{s.exceptions.length}</strong><span>Exceptions</span></article><article><strong>{s.observations.length}</strong><span>Observations</span></article><article><strong>{s.findings.filter(x=>x.status!=="CLOSED").length}</strong><span>Open findings</span></article><article><strong>{s.retests.length}</strong><span>Retests</span></article></section><OutcomesClient organizationId={organizationId} engagementId={engagementId} testResults={s.tests.map(x=>({id:x.id,label:`${x.result} · ${x.workpaper_title} / ${x.procedure_name}`}))} sources={sourceOptions} findings={findingOptions} evidence={s.evidence.map(x=>({id:x.id,label:x.filename}))} remediations={s.remediations.map(x=>({id:x.id,label:`${x.status} · ${x.plan.slice(0,60)}`}))} riskAcceptances={s.acceptances.filter(x=>x.approval_status==="PENDING").map(x=>({id:x.id,label:`Finding ${x.finding_id.slice(0,8)} · expires ${new Date(x.expires_at).toLocaleDateString()}`}))}/><section className="workspace-panel"><div className="section-heading"><h2>Finding register</h2></div><div className="signal-list">{s.findings.map(f=><article className="signal-card" key={f.id}><div className="signal-meta"><span>{f.finding_type}</span><span>{f.status}</span></div><h3>{f.title}</h3><p>Risk score {s.risks.find(r=>r.finding_id===f.id)?.score??"Not assessed"}</p><small>{s.remediations.filter(r=>r.finding_id===f.id).length} remediation(s) · {s.retests.filter(r=>r.finding_id===f.id).length} retest(s)</small></article>)}</div></section></main>;}
