import "server-only";

import { sql } from "drizzle-orm";
import type { AuthorizedTenantTransaction } from "@/auth/authorize";
import { permissions, requirePermission } from "@/auth/rbac";
import { recordDomainChange } from "@/domain/record-event";
import { validateException, validateFinding, validateObservation, validateRiskAssessment, type CreateExceptionInput, type CreateFindingInput, type CreateObservationInput, type AssessRiskInput } from "./validation";

export class FindingServiceError extends Error { constructor(message:string){super(message);this.name="FindingServiceError";} }
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function uuid(v:unknown,n:string){if(typeof v!=="string"||!UUID.test(v))throw new FindingServiceError(`${n} must be a UUID`);return v;}
function text(v:unknown,n:string,max=20000){if(typeof v!=="string"||!v.trim())throw new FindingServiceError(`${n} is required`);const x=v.trim();if(x.length>max)throw new FindingServiceError(`${n} too long`);return x;}
async function requireEngagement(tx:AuthorizedTenantTransaction,engagementId:string){const r=await tx.db.execute<{status:string}>(sql`select status::text from engagements where id=${engagementId}::uuid and organization_id=${tx.context.organizationId}::uuid`);if(!r.rows[0])throw new FindingServiceError("Engagement not found");return r.rows[0].status;}

export async function createObservation(tx:AuthorizedTenantTransaction,input:CreateObservationInput){requirePermission(tx.membership.role,permissions.findingCreate);const v=validateObservation(input);await requireEngagement(tx,v.engagementId);const r=await tx.db.execute<{id:string}>(sql`insert into observations(organization_id,engagement_id,workpaper_id,test_result_id,observation_type,description,significance,created_by) values(${tx.context.organizationId}::uuid,${v.engagementId}::uuid,${v.workpaperId}::uuid,${v.testResultId}::uuid,${v.observationType}::observation_type,${v.description},${v.significance??null},${tx.principal.userId}::uuid) returning id`);const row=r.rows[0];if(!row)throw new FindingServiceError("Observation write failed");await recordDomainChange(tx,{eventType:"engagement.observation.created",aggregateType:"engagement",aggregateId:v.engagementId,action:"engagement.observation.create",entityType:"observation",entityId:row.id,payload:{testResultId:v.testResultId},newValues:{observationType:v.observationType,description:v.description}});return row;}

export async function createException(tx:AuthorizedTenantTransaction,input:CreateExceptionInput){requirePermission(tx.membership.role,permissions.findingCreate);const v=validateException(input);await requireEngagement(tx,v.engagementId);const r=await tx.db.execute<{id:string}>(sql`insert into exceptions(organization_id,engagement_id,workpaper_id,test_result_id,description,severity,created_by) values(${tx.context.organizationId}::uuid,${v.engagementId}::uuid,${v.workpaperId}::uuid,${v.testResultId}::uuid,${v.description},${v.severity},${tx.principal.userId}::uuid) returning id`);const row=r.rows[0];if(!row)throw new FindingServiceError("Exception write failed");await recordDomainChange(tx,{eventType:"engagement.exception.created",aggregateType:"engagement",aggregateId:v.engagementId,action:"engagement.exception.create",entityType:"exception",entityId:row.id,payload:{testResultId:v.testResultId},newValues:{severity:v.severity,description:v.description}});return row;}

export async function createFinding(tx:AuthorizedTenantTransaction,input:CreateFindingInput){requirePermission(tx.membership.role,permissions.findingCreate);const v=validateFinding(input);await requireEngagement(tx,v.engagementId);const r=await tx.db.execute<{id:string}>(sql`insert into findings(organization_id,engagement_id,exception_id,observation_id,title,description,finding_type,created_by) values(${tx.context.organizationId}::uuid,${v.engagementId}::uuid,${v.exceptionId??null}::uuid,${v.observationId??null}::uuid,${v.title},${v.description},${v.findingType},${tx.principal.userId}::uuid) returning id`);const row=r.rows[0];if(!row)throw new FindingServiceError("Finding write failed");await recordDomainChange(tx,{eventType:"engagement.finding.created",aggregateType:"engagement",aggregateId:v.engagementId,action:"engagement.finding.create",entityType:"finding",entityId:row.id,payload:{exceptionId:v.exceptionId??null,observationId:v.observationId??null},newValues:{title:v.title,findingType:v.findingType}});return row;}

export async function assessFindingRisk(tx:AuthorizedTenantTransaction,input:AssessRiskInput){requirePermission(tx.membership.role,permissions.findingUpdate);const v=validateRiskAssessment(input);const f=await tx.db.execute<{engagement_id:string}>(sql`select engagement_id from findings where id=${v.findingId}::uuid and organization_id=${tx.context.organizationId}::uuid`);const engagementId=f.rows[0]?.engagement_id;if(!engagementId)throw new FindingServiceError("Finding not found");const r=await tx.db.execute<{id:string}>(sql`insert into risks(organization_id,engagement_id,finding_id,likelihood,impact,score,method_version,rationale,assessed_by) values(${tx.context.organizationId}::uuid,${engagementId}::uuid,${v.findingId}::uuid,${v.likelihood},${v.impact},${v.score},${v.methodVersion},${v.rationale},${tx.principal.userId}::uuid) returning id`);const row=r.rows[0];if(!row)throw new FindingServiceError("Risk write failed");await recordDomainChange(tx,{eventType:"engagement.finding.risk_assessed",aggregateType:"engagement",aggregateId:engagementId,action:"engagement.finding.risk_assess",entityType:"risk",entityId:row.id,payload:{findingId:v.findingId},newValues:{likelihood:v.likelihood,impact:v.impact,score:v.score,methodVersion:v.methodVersion}});return row;}

export async function createRemediation(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.findingUpdate);const findingId=uuid(input.findingId,"findingId"),plan=text(input.plan,"plan");const f=await tx.db.execute<{engagement_id:string}>(sql`select engagement_id from findings where id=${findingId}::uuid and organization_id=${tx.context.organizationId}::uuid`);const engagementId=f.rows[0]?.engagement_id;if(!engagementId)throw new FindingServiceError("Finding not found");const owner=input.ownerUserId?uuid(input.ownerUserId,"ownerUserId"):null;const target=typeof input.targetDate==="string"&&input.targetDate?input.targetDate:null;const r=await tx.db.execute<{id:string}>(sql`insert into remediations(organization_id,engagement_id,finding_id,owner_user_id,plan,target_date) values(${tx.context.organizationId}::uuid,${engagementId}::uuid,${findingId}::uuid,${owner}::uuid,${plan},${target}::date) returning id`);const row=r.rows[0];if(!row)throw new FindingServiceError("Remediation write failed");return row;}

export async function completeRemediation(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.findingUpdate);const id=uuid(input.remediationId,"remediationId");const r=await tx.db.execute<{engagement_id:string}>(sql`update remediations set status='COMPLETED',completed_at=now(),completed_by=${tx.principal.userId}::uuid,updated_at=now() where id=${id}::uuid and organization_id=${tx.context.organizationId}::uuid returning engagement_id`);if(!r.rows[0])throw new FindingServiceError("Remediation not found");return {id};}

export async function createRiskAcceptance(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.findingUpdate);const findingId=uuid(input.findingId,"findingId"),rationale=text(input.rationale,"rationale");const expires=text(input.expiresAt,"expiresAt",100),review=text(input.reviewDueAt,"reviewDueAt",100);const f=await tx.db.execute<{engagement_id:string}>(sql`select engagement_id from findings where id=${findingId}::uuid and organization_id=${tx.context.organizationId}::uuid`);const engagementId=f.rows[0]?.engagement_id;if(!engagementId)throw new FindingServiceError("Finding not found");const r=await tx.db.execute<{id:string}>(sql`insert into risk_acceptances(organization_id,engagement_id,finding_id,accepted_by,rationale,expires_at,review_due_at) values(${tx.context.organizationId}::uuid,${engagementId}::uuid,${findingId}::uuid,${tx.principal.userId}::uuid,${rationale},${expires}::timestamptz,${review}::timestamptz) returning id`);const row=r.rows[0];if(!row)throw new FindingServiceError("Risk acceptance write failed");return row;}

export async function approveRiskAcceptance(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.findingClose);const id=uuid(input.riskAcceptanceId,"riskAcceptanceId");const r=await tx.db.execute<{accepted_by:string}>(sql`select accepted_by from risk_acceptances where id=${id}::uuid and organization_id=${tx.context.organizationId}::uuid`);const row=r.rows[0];if(!row)throw new FindingServiceError("Risk acceptance not found");if(row.accepted_by===tx.principal.userId)throw new FindingServiceError("Risk acceptance requires independent approval");await tx.db.execute(sql`update risk_acceptances set approval_status='APPROVED',approved_by=${tx.principal.userId}::uuid,approved_at=now() where id=${id}::uuid`);return {id};}

export async function createRetest(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.findingUpdate);const findingId=uuid(input.findingId,"findingId"),remediationId=input.remediationId?uuid(input.remediationId,"remediationId"):null,evidenceId=input.evidenceId?uuid(input.evidenceId,"evidenceId"):null,result=text(input.result,"result",40),conclusion=text(input.conclusion,"conclusion");const f=await tx.db.execute<{engagement_id:string}>(sql`select engagement_id from findings where id=${findingId}::uuid and organization_id=${tx.context.organizationId}::uuid`);const engagementId=f.rows[0]?.engagement_id;if(!engagementId)throw new FindingServiceError("Finding not found");const r=await tx.db.execute<{id:string}>(sql`insert into retests(organization_id,engagement_id,finding_id,remediation_id,result,evidence_id,tested_by,conclusion) values(${tx.context.organizationId}::uuid,${engagementId}::uuid,${findingId}::uuid,${remediationId}::uuid,${result}::test_result_status,${evidenceId}::uuid,${tx.principal.userId}::uuid,${conclusion}) returning id`);const row=r.rows[0];if(!row)throw new FindingServiceError("Retest write failed");return row;}

export async function closeFinding(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.findingClose);const id=uuid(input.findingId,"findingId");const r=await tx.db.execute<{engagement_id:string}>(sql`update findings set status='CLOSED',updated_at=now() where id=${id}::uuid and organization_id=${tx.context.organizationId}::uuid returning engagement_id`);const row=r.rows[0];if(!row)throw new FindingServiceError("Finding not found");return {id};}
