"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

type Option={id:string;label:string};
export function ExecutionClient({organizationId,engagementId,requirements,scopes,workpapers,pbcRequests,completedPbcRequests}:{organizationId:string;engagementId:string;requirements:readonly Option[];scopes:readonly Option[];workpapers:readonly Option[];pbcRequests:readonly Option[];completedPbcRequests:readonly Option[]}){
 const router=useRouter();const[message,setMessage]=useState<string|null>(null);const[busy,setBusy]=useState(false);
 async function send(action:string,input:Record<string,unknown>){setBusy(true);setMessage(null);const r=await fetch(`/api/organizations/${organizationId}/engagements/${engagementId}/execution`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,input})});const b=await r.json();setBusy(false);if(!r.ok){setMessage(b.message??"Action rejected");return;}setMessage("Saved");router.refresh();}
 return <section className="workspace-panel"><div className="section-heading"><div><p className="eyebrow">Execution actions</p><h2>Sampling and testing setup</h2></div></div><div className="organization-grid">
 <form className="auth-form" onSubmit={(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);void send("create_sample",{requirementId:f.get("requirementId")||null,scopeId:f.get("scopeId")||null,populationDescription:f.get("populationDescription"),populationSize:f.get("populationSize")?Number(f.get("populationSize")):null,samplingMethod:f.get("samplingMethod"),sampleSize:f.get("sampleSize")?Number(f.get("sampleSize")):null,selectionBasis:f.get("selectionBasis")});}}><h3>Create sample</h3><label>Requirement<select name="requirementId"><option value="">None</option>{requirements.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label>Scope<select name="scopeId"><option value="">None</option>{scopes.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label>Population<textarea name="populationDescription" required/></label><label>Population size<input name="populationSize" type="number" min="0"/></label><label>Method<input name="samplingMethod" required/></label><label>Sample size<input name="sampleSize" type="number" min="0"/></label><label>Selection basis<textarea name="selectionBasis" required/></label><button disabled={busy}>Create sample</button></form>
 <form className="auth-form" onSubmit={(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);void send("create_workpaper",{title:f.get("title")});}}><h3>Create workpaper</h3><label>Title<input name="title" required/></label><button disabled={busy}>Create workpaper</button></form>
 {workpapers.map(x=><form className="auth-form" key={x.id} onSubmit={(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);if(window.confirm(`Update workpaper “${x.label}”? A new version will be recorded.`))void send("update_workpaper",{workpaperId:x.id,title:f.get("title"),changeReason:f.get("changeReason")});}}><h3>Edit workpaper</h3><label>Title<input name="title" defaultValue={x.label} required/></label><label>Change reason<input name="changeReason" placeholder="Reason for this version" required/></label><button disabled={busy}>Save new version</button></form>)}
 <form className="auth-form" onSubmit={(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);void send("create_pbc",{workpaperId:f.get("workpaperId")||null,title:f.get("title"),description:f.get("description")||null,expectedEvidence:f.get("expectedEvidence"),dueAt:f.get("dueAt")||null});}}><h3>Create PBC request</h3><label>Workpaper<select name="workpaperId"><option value="">None</option>{workpapers.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label>Title<input name="title" required/></label><label>Description<textarea name="description"/></label><label>Expected evidence<textarea name="expectedEvidence" required/></label><label>Due<input name="dueAt" type="datetime-local"/></label><button disabled={busy}>Create PBC</button></form>
 {pbcRequests.length?<form className="auth-form" onSubmit={(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);const request=f.get("pbcRequestId");if(typeof request==="string"&&window.confirm("Complete this PBC request? DPM-Assure will only allow completion when active linked evidence exists."))void send("complete_pbc",{pbcRequestId:request});}}><h3>Complete PBC request</h3><p className="lede compact">Completion is controlled: the engagement must be in testing and the request must have active linked evidence.</p><label>Request<select name="pbcRequestId" required defaultValue=""><option value="" disabled>Select active request</option>{pbcRequests.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><button disabled={busy}>Verify evidence and complete</button></form>:null}
 {completedPbcRequests.length?<form className="auth-form" onSubmit={(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);const request=f.get("pbcRequestId"),reason=f.get("reason");if(typeof request==="string"&&typeof reason==="string"&&window.confirm("Close this completed PBC request? The closure reason will be retained in the audit history."))void send("close_pbc",{pbcRequestId:request,reason});}}><h3>Close completed PBC</h3><p className="lede compact">An independent review action closes only a completed request. The reason is retained in the immutable audit history.</p><label>Request<select name="pbcRequestId" required defaultValue=""><option value="" disabled>Select completed request</option>{completedPbcRequests.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label>Closure reason<textarea name="reason" required/></label><button disabled={busy}>Close PBC</button></form>:null}
 {pbcRequests.length?<form className="auth-form" onSubmit={(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);const request=f.get("pbcRequestId"),reason=f.get("reason");if(typeof request==="string"&&typeof reason==="string"&&window.confirm("Cancel this PBC request? The assigned client will no longer be able to respond or upload evidence."))void send("cancel_pbc",{pbcRequestId:request,reason});}}><h3>Cancel active PBC</h3><p className="lede compact">Cancellation removes any client assignment and preserves the rationale in the audit history.</p><label>Request<select name="pbcRequestId" required defaultValue=""><option value="" disabled>Select active request</option>{pbcRequests.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label>Cancellation reason<textarea name="reason" required/></label><button className="secondary-button" disabled={busy}>Cancel PBC</button></form>:null}
 </div>{message&&<p className="form-message">{message}</p>}</section>;
}
