import "server-only";

import { sql } from "drizzle-orm";
import type { AuthorizedTenantTransaction } from "@/auth/authorize";
import { permissions, requirePermission } from "@/auth/rbac";
import { recordDomainChange } from "@/domain/record-event";

export class ClientPortalError extends Error { constructor(message:string){super(message);this.name="ClientPortalError";} }
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function uuid(v:unknown,n:string){if(typeof v!=="string"||!UUID.test(v))throw new ClientPortalError(`${n} must be a UUID`);return v;}
function text(v:unknown,n:string,max=10000){if(typeof v!=="string"||!v.trim())throw new ClientPortalError(`${n} is required`);const x=v.trim();if(x.length>max)throw new ClientPortalError(`${n} must not exceed ${max} characters`);return x;}

export async function grantClientAccess(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.organizationManageUsers);const clientId=uuid(input.clientId,"clientId"),userId=uuid(input.userId,"userId");const r=await tx.db.execute<{id:string}>(sql`insert into client_user_access(organization_id,client_id,user_id,status,granted_by) values(${tx.context.organizationId}::uuid,${clientId}::uuid,${userId}::uuid,'ACTIVE',${tx.principal.userId}::uuid) on conflict(client_id,user_id) do update set status='ACTIVE',granted_by=excluded.granted_by,granted_at=now(),updated_at=now() returning id`);const row=r.rows[0];if(!row)throw new ClientPortalError("Client access grant failed");await recordDomainChange(tx,{eventType:"client.portal_access.granted",aggregateType:"client",aggregateId:clientId,action:"client.portal_access.grant",entityType:"client_user_access",entityId:row.id,payload:{userId},newValues:{status:"ACTIVE"}});return row;}

export async function revokeClientAccess(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.organizationManageUsers);const accessId=uuid(input.accessId,"accessId");const r=await tx.db.execute<{id:string;client_id:string;user_id:string}>(sql`update client_user_access set status='INACTIVE',updated_at=now() where id=${accessId}::uuid and organization_id=${tx.context.organizationId}::uuid returning id,client_id,user_id`);const row=r.rows[0];if(!row)throw new ClientPortalError("Client access mapping not found");await recordDomainChange(tx,{eventType:"client.portal_access.revoked",aggregateType:"client",aggregateId:row.client_id,action:"client.portal_access.revoke",entityType:"client_user_access",entityId:row.id,payload:{userId:row.user_id},newValues:{status:"INACTIVE"}});return {id:row.id};}

export async function assignPbcToClientUser(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.workpaperUpdate);const pbcRequestId=uuid(input.pbcRequestId,"pbcRequestId"),userId=uuid(input.userId,"userId");const r=await tx.db.execute<{id:string;engagement_id:string}>(sql`update pbc_requests p set assigned_to=${userId}::uuid,status=case when p.status='OPEN' then 'IN_PROGRESS'::workflow_status else p.status end,updated_at=now() where p.id=${pbcRequestId}::uuid and exists(select 1 from engagements e where e.id=p.engagement_id and e.organization_id=${tx.context.organizationId}::uuid) returning id,engagement_id`);const row=r.rows[0];if(!row)throw new ClientPortalError("PBC request not found");await recordDomainChange(tx,{eventType:"engagement.pbc.assigned_to_client",aggregateType:"engagement",aggregateId:row.engagement_id,action:"engagement.pbc.assign_client",entityType:"pbc_request",entityId:row.id,payload:{userId},newValues:{assignedTo:userId}});return {id:row.id};}

export async function listClientPortalRequests(tx:AuthorizedTenantTransaction){requirePermission(tx.membership.role,permissions.clientPortalRead);const r=await tx.db.execute<{id:string;title:string;description:string|null;status:string;due_at:string|null;expected_evidence:string|null;engagement_name:string;client_name:string;responses:string}>(sql`
 select p.id,p.title,p.description,p.status::text,p.due_at::text,p.expected_evidence,e.name engagement_name,c.name client_name,
   (select count(*)::text from client_pbc_responses r where r.pbc_request_id=p.id) responses
 from pbc_requests p
 join engagements e on e.id=p.engagement_id
 join clients c on c.id=e.client_id
 join client_user_access cua on cua.organization_id=e.organization_id and cua.client_id=e.client_id and cua.user_id=${tx.principal.userId}::uuid and cua.status='ACTIVE'
 where e.organization_id=${tx.context.organizationId}::uuid and p.assigned_to=${tx.principal.userId}::uuid
 order by p.due_at nulls last,p.created_at desc`);return r.rows;}

export async function submitPbcResponse(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.clientPbcRespond);const pbcRequestId=uuid(input.pbcRequestId,"pbcRequestId"),responseText=text(input.responseText,"responseText");const request=(await tx.db.execute<{engagement_id:string;status:string}>(sql`select p.engagement_id,p.status::text from pbc_requests p join engagements e on e.id=p.engagement_id join client_user_access cua on cua.organization_id=e.organization_id and cua.client_id=e.client_id and cua.user_id=${tx.principal.userId}::uuid and cua.status='ACTIVE' where p.id=${pbcRequestId}::uuid and p.assigned_to=${tx.principal.userId}::uuid and e.organization_id=${tx.context.organizationId}::uuid`)).rows[0];if(!request)throw new ClientPortalError("Assigned PBC request not found");if(["CLOSED","CANCELLED"].includes(request.status))throw new ClientPortalError("This PBC request no longer accepts responses");const r=await tx.db.execute<{id:string}>(sql`insert into client_pbc_responses(organization_id,pbc_request_id,submitted_by,response_text) values(${tx.context.organizationId}::uuid,${pbcRequestId}::uuid,${tx.principal.userId}::uuid,${responseText}) returning id`);const row=r.rows[0];if(!row)throw new ClientPortalError("PBC response write failed");await recordDomainChange(tx,{eventType:"engagement.pbc.client_response",aggregateType:"engagement",aggregateId:request.engagement_id,action:"client.pbc.respond",entityType:"client_pbc_response",entityId:row.id,payload:{pbcRequestId},newValues:{responseText}});return row;}
