import Link from "next/link";
import { redirect } from "next/navigation";
import { sql } from "drizzle-orm";
import { getCurrentUserContext } from "@/auth/current-user-context";
import { withAuthorizedTenantTransaction } from "@/auth/authorize";
import { permissions } from "@/auth/rbac";
import { ClientAccessClient } from "./ClientAccessClient";

export const dynamic="force-dynamic";
type PageProps={params:Promise<{organizationId:string}>};
export default async function ClientAccessPage({params}:PageProps){const{organizationId}=await params;const current=await getCurrentUserContext();if(!current)redirect("/login");const membership=current.memberships.find(x=>x.organizationId===organizationId);if(!membership)redirect("/dashboard");if(membership.role!=="ORG_ADMIN"&&membership.role!=="SUPER_ADMIN")redirect("/dashboard");const s=await withAuthorizedTenantTransaction({principal:current.principal,organizationId,requestId:crypto.randomUUID(),permission:permissions.organizationManageUsers},async(tx)=>{const clients=(await tx.db.execute<{id:string;name:string}>(sql`select id,name from clients where organization_id=${organizationId}::uuid and status='ACTIVE' order by name`)).rows;const users=(await tx.db.execute<{id:string;email:string;display_name:string}>(sql`select u.id,u.email,u.display_name from memberships m join users u on u.id=m.user_id where m.organization_id=${organizationId}::uuid and m.status='ACTIVE' and m.role='CLIENT' order by u.email`)).rows;const mappings=(await tx.db.execute<{id:string;client_id:string;user_id:string;status:string;client_name:string;email:string}>(sql`select cua.id,cua.client_id,cua.user_id,cua.status::text,c.name client_name,u.email from client_user_access cua join clients c on c.id=cua.client_id join users u on u.id=cua.user_id where cua.organization_id=${organizationId}::uuid order by c.name,u.email`)).rows;const pbc=(await tx.db.execute<{id:string;title:string;engagement_name:string;assigned_to:string|null}>(sql`select p.id,p.title,e.name engagement_name,p.assigned_to from pbc_requests p join engagements e on e.id=p.engagement_id where e.organization_id=${organizationId}::uuid and p.status not in('CLOSED','CANCELLED') order by p.created_at desc`)).rows;return{clients,users,mappings,pbc};});return <main className="dashboard-shell"><Link className="back-link" href="/dashboard">← Dashboard</Link><header className="dashboard-header"><div><p className="eyebrow">Organization administration</p><h1>Client portal access</h1><p className="lede compact">Organization membership never grants client data access by itself. Map each CLIENT user to an explicit client entity before assigning PBC requests.</p></div><span className="role-badge">{membership.role}</span></header><ClientAccessClient organizationId={organizationId} clients={s.clients.map(x=>({id:x.id,label:x.name}))} clientUsers={s.users.map(x=>({id:x.id,label:`${x.display_name} · ${x.email}`}))} mappings={s.mappings.map(x=>({id:x.id,clientId:x.client_id,userId:x.user_id,label:`${x.client_name} · ${x.email}`,status:x.status}))} pbcRequests={s.pbc.map(x=>({id:x.id,label:`${x.engagement_name} · ${x.title}${x.assigned_to?" · assigned":""}`}))}/></main>;}
