import "server-only";

import { sql } from "drizzle-orm";
import type { AuthorizedTenantTransaction } from "@/auth/authorize";
import { permissions, requirePermission } from "@/auth/rbac";
import { recordDomainChange } from "@/domain/record-event";

export class ClosureServiceError extends Error { constructor(message:string){super(message);this.name="ClosureServiceError";} }
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const SHA=/^[0-9a-f]{64}$/i;
function uuid(v:unknown,n:string){if(typeof v!=="string"||!UUID.test(v))throw new ClosureServiceError(`${n} must be a UUID`);return v;}
function text(v:unknown,n:string,max=30000){if(typeof v!=="string"||!v.trim())throw new ClosureServiceError(`${n} is required`);const x=v.trim();if(x.length>max)throw new ClosureServiceError(`${n} too long`);return x;}
async function engagementStatus(tx:AuthorizedTenantTransaction,id:string){const r=await tx.db.execute<{status:string;frozen_at:string|null}>(sql`select status::text,frozen_at::text from engagements where id=${id}::uuid and organization_id=${tx.context.organizationId}::uuid`);if(!r.rows[0])throw new ClosureServiceError("Engagement not found");return r.rows[0];}

export async function moveToReview(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.engagementUpdate);const engagementId=uuid(input.engagementId,"engagementId");await engagementStatus(tx,engagementId);await tx.db.execute(sql`update engagements set status='REVIEW',updated_at=now() where id=${engagementId}::uuid and organization_id=${tx.context.organizationId}::uuid and status='TESTING'`);await recordDomainChange(tx,{eventType:"engagement.review_started",aggregateType:"engagement",aggregateId:engagementId,action:"engagement.review.start",entityType:"engagement",entityId:engagementId,payload:{from:"TESTING",to:"REVIEW"},oldValues:{status:"TESTING"},newValues:{status:"REVIEW"}});return{engagementId};}

export async function reviewWorkpaper(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.workpaperReview);const engagementId=uuid(input.engagementId,"engagementId"),workpaperId=uuid(input.workpaperId,"workpaperId");const status=text(input.status,"status",20);if(!["APPROVED","REJECTED"].includes(status))throw new ClosureServiceError("Review status must be APPROVED or REJECTED");const comments=typeof input.comments==="string"?input.comments.trim()||null:null;const r=await tx.db.execute<{id:string}>(sql`insert into reviews(engagement_id,workpaper_id,reviewer_id,status,comments,reviewed_at) values(${engagementId}::uuid,${workpaperId}::uuid,${tx.principal.userId}::uuid,${status}::review_status,${comments},now()) returning id`);const row=r.rows[0];if(!row)throw new ClosureServiceError("Review write failed");return row;}

export async function signoffEngagement(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.engagementSignoff);const engagementId=uuid(input.engagementId,"engagementId"),statement=text(input.statement,"statement");const role=tx.membership.role;if(role!=="AUDIT_MANAGER"&&role!=="REVIEWER"&&role!=="SUPER_ADMIN"&&role!=="ORG_ADMIN")throw new ClosureServiceError("Sign-off requires an assurance reviewer role");const signoffRole=role==="SUPER_ADMIN"||role==="ORG_ADMIN"?"AUDIT_MANAGER":role;const r=await tx.db.execute<{id:string}>(sql`insert into signoffs(engagement_id,reviewed_by,role,status,statement,signed_at,signoff_type) values(${engagementId}::uuid,${tx.principal.userId}::uuid,${signoffRole}::membership_role,'APPROVED',${statement},now(),'ENGAGEMENT_FINAL') returning id`);const row=r.rows[0];if(!row)throw new ClosureServiceError("Sign-off write failed");return row;}

export async function generateReport(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.reportGenerate);const engagementId=uuid(input.engagementId,"engagementId"),reportType=text(input.reportType,"reportType",100);const content=input.content&&typeof input.content==="object"?input.content:{};const latest=await tx.db.execute<{version:number}>(sql`select coalesce(max(version),0)::int as version from reports where engagement_id=${engagementId}::uuid`);const version=(latest.rows[0]?.version??0)+1;const r=await tx.db.execute<{id:string}>(sql`insert into reports(engagement_id,version,status,report_type,content,generated_by) values(${engagementId}::uuid,${version},'PENDING',${reportType},${JSON.stringify(content)}::jsonb,${tx.principal.userId}::uuid) returning id`);const row=r.rows[0];if(!row)throw new ClosureServiceError("Report write failed");return{...row,version};}

export async function approveReport(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.reportApprove);const reportId=uuid(input.reportId,"reportId");const r=await tx.db.execute<{generated_by:string;engagement_id:string}>(sql`select generated_by,engagement_id from reports where id=${reportId}::uuid`);const row=r.rows[0];if(!row)throw new ClosureServiceError("Report not found");if(row.generated_by===tx.principal.userId)throw new ClosureServiceError("Report generator cannot approve the same report");await tx.db.execute(sql`update reports set status='APPROVED',approved_by=${tx.principal.userId}::uuid,approved_at=now(),updated_at=now() where id=${reportId}::uuid`);return{reportId};}

export async function closeEngagement(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.engagementClose);const engagementId=uuid(input.engagementId,"engagementId");const s=await engagementStatus(tx,engagementId);if(s.status!=="REVIEW")throw new ClosureServiceError("Final assurance closure requires REVIEW status");await tx.db.execute(sql`update engagements set status='CLOSED',updated_at=now() where id=${engagementId}::uuid and organization_id=${tx.context.organizationId}::uuid`);return{engagementId};}

export async function freezeEngagement(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.engagementFreeze);const engagementId=uuid(input.engagementId,"engagementId"),reason=text(input.freezeReason,"freezeReason"),snapshotHash=text(input.snapshotHash,"snapshotHash",64).toLowerCase();if(!SHA.test(snapshotHash))throw new ClosureServiceError("snapshotHash must be SHA-256 hex");const latest=await tx.db.execute<{version:number}>(sql`select coalesce(max(version),0)::int as version from audit_freezes where engagement_id=${engagementId}::uuid`);const version=(latest.rows[0]?.version??0)+1;const r=await tx.db.execute<{id:string}>(sql`insert into audit_freezes(engagement_id,version,frozen_by,freeze_reason,snapshot_hash) values(${engagementId}::uuid,${version},${tx.principal.userId}::uuid,${reason},${snapshotHash}) returning id`);const row=r.rows[0];if(!row)throw new ClosureServiceError("Audit freeze failed");return{...row,version};}

export async function archiveEngagement(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.engagementFreeze);const engagementId=uuid(input.engagementId,"engagementId"),freezeId=uuid(input.auditFreezeId,"auditFreezeId"),reason=text(input.archiveReason,"archiveReason");const retention=typeof input.retentionUntil==="string"&&input.retentionUntil?input.retentionUntil:null;const r=await tx.db.execute<{id:string}>(sql`insert into engagement_archives(organization_id,engagement_id,audit_freeze_id,archived_by,retention_until,archive_reason) values(${tx.context.organizationId}::uuid,${engagementId}::uuid,${freezeId}::uuid,${tx.principal.userId}::uuid,${retention}::timestamptz,${reason}) returning id`);const row=r.rows[0];if(!row)throw new ClosureServiceError("Archive failed");return row;}

export async function createMonitoringProgram(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.complianceMonitoringManage);const baseline=uuid(input.baselineEngagementId,"baselineEngagementId"),name=text(input.name,"name",300),nextDue=text(input.nextDueAt,"nextDueAt",100);const cadence=Number(input.cadenceDays);if(!Number.isSafeInteger(cadence)||cadence<=0)throw new ClosureServiceError("cadenceDays must be positive");const r=await tx.db.execute<{id:string}>(sql`insert into monitoring_programs(organization_id,baseline_engagement_id,name,cadence_days,next_due_at,created_by) values(${tx.context.organizationId}::uuid,${baseline}::uuid,${name},${cadence},${nextDue}::timestamptz,${tx.principal.userId}::uuid) returning id`);const row=r.rows[0];if(!row)throw new ClosureServiceError("Monitoring program failed");return row;}

export async function recordMonitoringCheck(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.complianceMonitoringManage);const programId=uuid(input.monitoringProgramId,"monitoringProgramId"),result=text(input.result,"result",40),summary=text(input.summary,"summary");if(!["CLEAR","CHANGE_DETECTED","INSUFFICIENT_EVIDENCE"].includes(result))throw new ClosureServiceError("Invalid monitoring result");const evidenceId=input.evidenceId?uuid(input.evidenceId,"evidenceId"):null;const r=await tx.db.execute<{id:string}>(sql`insert into monitoring_checks(organization_id,monitoring_program_id,result,summary,checked_by,evidence_id) values(${tx.context.organizationId}::uuid,${programId}::uuid,${result}::monitoring_result,${summary},${tx.principal.userId}::uuid,${evidenceId}::uuid) returning id`);const row=r.rows[0];if(!row)throw new ClosureServiceError("Monitoring check failed");return row;}

export async function recordChangeEvent(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.complianceMonitoringManage);const baseline=uuid(input.baselineEngagementId,"baselineEngagementId"),changeType=text(input.changeType,"changeType",100),description=text(input.description,"description");const checkId=input.monitoringCheckId?uuid(input.monitoringCheckId,"monitoringCheckId"):null,evidenceId=input.evidenceId?uuid(input.evidenceId,"evidenceId"):null;if(!checkId&&!evidenceId)throw new ClosureServiceError("Change event requires monitoringCheckId or evidenceId");const r=await tx.db.execute<{id:string}>(sql`insert into change_events(organization_id,baseline_engagement_id,monitoring_check_id,evidence_id,change_type,description,detected_by) values(${tx.context.organizationId}::uuid,${baseline}::uuid,${checkId}::uuid,${evidenceId}::uuid,${changeType},${description},${tx.principal.userId}::uuid) returning id`);const row=r.rows[0];if(!row)throw new ClosureServiceError("Change event failed");return row;}

export async function recordReassessment(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.complianceMonitoringManage);const baseline=uuid(input.baselineEngagementId,"baselineEngagementId"),changeId=uuid(input.changeEventId,"changeEventId"),decision=text(input.decision,"decision",40),rationale=text(input.rationale,"rationale");if(!["NO_ACTION","UPDATE_MONITORING","NEW_ENGAGEMENT"].includes(decision))throw new ClosureServiceError("Invalid reassessment decision");const successor=input.successorEngagementId?uuid(input.successorEngagementId,"successorEngagementId"):null;const r=await tx.db.execute<{id:string}>(sql`insert into reassessments(organization_id,baseline_engagement_id,change_event_id,decision,rationale,assessed_by,successor_engagement_id) values(${tx.context.organizationId}::uuid,${baseline}::uuid,${changeId}::uuid,${decision}::reassessment_decision,${rationale},${tx.principal.userId}::uuid,${successor}::uuid) returning id`);const row=r.rows[0];if(!row)throw new ClosureServiceError("Reassessment failed");return row;}
