import "server-only";

import { createHash } from "node:crypto";
import { sql } from "drizzle-orm";
import type { AuthorizedTenantTransaction } from "@/auth/authorize";
import { permissions, requirePermission } from "@/auth/rbac";
import { recordDomainChange } from "@/domain/record-event";

export class FinalizationError extends Error { constructor(message:string){super(message);this.name="FinalizationError";} }
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function uuid(v:unknown,n:string){if(typeof v!=="string"||!UUID.test(v))throw new FinalizationError(`${n} must be a UUID`);return v;}
function text(v:unknown,n:string,max=30000){if(typeof v!=="string"||!v.trim())throw new FinalizationError(`${n} is required`);const x=v.trim();if(x.length>max)throw new FinalizationError(`${n} must not exceed ${max} characters`);return x;}
async function engagementStatus(tx:AuthorizedTenantTransaction,id:string){const r=await tx.db.execute<{status:string}>(sql`select status::text from engagements where id=${id}::uuid and organization_id=${tx.context.organizationId}::uuid`);if(!r.rows[0])throw new FinalizationError("Engagement not found");return r.rows[0].status;}

export async function enterReview(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.engagementUpdate);const engagementId=uuid(input.engagementId,"engagementId");const status=await engagementStatus(tx,engagementId);if(status!=="TESTING")throw new FinalizationError("Only TESTING engagements can enter REVIEW");await tx.db.execute(sql`update engagements set status='REVIEW',updated_at=now() where id=${engagementId}::uuid and organization_id=${tx.context.organizationId}::uuid`);await recordDomainChange(tx,{eventType:"engagement.review.entered",aggregateType:"engagement",aggregateId:engagementId,action:"engagement.enter_review",entityType:"engagement",entityId:engagementId,payload:{},newValues:{status:"REVIEW"}});return {id:engagementId,status:"REVIEW"};}

export async function reviewWorkpaper(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.workpaperReview);const engagementId=uuid(input.engagementId,"engagementId"),workpaperId=uuid(input.workpaperId,"workpaperId"),status=text(input.status,"status",20);if(!["APPROVED","REJECTED"].includes(status))throw new FinalizationError("Review status must be APPROVED or REJECTED");const comments=typeof input.comments==="string"&&input.comments.trim()?input.comments.trim():null;const r=await tx.db.execute<{id:string}>(sql`insert into reviews(engagement_id,workpaper_id,reviewer_id,status,comments,reviewed_at) values(${engagementId}::uuid,${workpaperId}::uuid,${tx.principal.userId}::uuid,${status}::review_status,${comments},now()) returning id`);const row=r.rows[0];if(!row)throw new FinalizationError("Review write failed");await recordDomainChange(tx,{eventType:"engagement.workpaper.reviewed",aggregateType:"engagement",aggregateId:engagementId,action:"engagement.workpaper.review",entityType:"review",entityId:row.id,payload:{workpaperId},newValues:{status,comments}});return row;}

export async function signoffEngagement(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.engagementSignoff);const engagementId=uuid(input.engagementId,"engagementId"),statement=text(input.statement,"statement");if((await engagementStatus(tx,engagementId))!=="REVIEW")throw new FinalizationError("Final sign-off is only allowed in REVIEW");const role=tx.membership.role;if(role!=="AUDIT_MANAGER"&&role!=="REVIEWER")throw new FinalizationError("Final sign-off requires AUDIT_MANAGER or REVIEWER");const r=await tx.db.execute<{id:string}>(sql`insert into signoffs(engagement_id,reviewed_by,role,status,statement,signed_at,signoff_type) values(${engagementId}::uuid,${tx.principal.userId}::uuid,${role}::membership_role,'APPROVED',${statement},now(),'ENGAGEMENT_FINAL') returning id`);const row=r.rows[0];if(!row)throw new FinalizationError("Sign-off write failed");await recordDomainChange(tx,{eventType:"engagement.signoff.approved",aggregateType:"engagement",aggregateId:engagementId,action:"engagement.signoff",entityType:"signoff",entityId:row.id,payload:{role},newValues:{status:"APPROVED",statement}});return row;}

export async function generateReport(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.reportGenerate);const engagementId=uuid(input.engagementId,"engagementId"),reportType=typeof input.reportType==="string"&&input.reportType.trim()?input.reportType.trim():"FINAL_ASSURANCE";const summary=typeof input.summary==="string"?input.summary.trim():"";const counts=(await tx.db.execute<{workpapers:string;findings:string;closed_findings:string}>(sql`select (select count(*)::text from workpapers where engagement_id=${engagementId}::uuid) workpapers,(select count(*)::text from findings where engagement_id=${engagementId}::uuid) findings,(select count(*)::text from findings where engagement_id=${engagementId}::uuid and status='CLOSED') closed_findings`)).rows[0];const versionRow=(await tx.db.execute<{version:number}>(sql`select coalesce(max(version),0)+1 as version from reports where engagement_id=${engagementId}::uuid`)).rows[0];const version=Number(versionRow?.version??1);const content={summary,generatedAt:new Date().toISOString(),workpapers:Number(counts?.workpapers??0),findings:Number(counts?.findings??0),closedFindings:Number(counts?.closed_findings??0)};const r=await tx.db.execute<{id:string}>(sql`insert into reports(engagement_id,version,status,report_type,content,generated_by) values(${engagementId}::uuid,${version},'PENDING',${reportType},${JSON.stringify(content)}::jsonb,${tx.principal.userId}::uuid) returning id`);const row=r.rows[0];if(!row)throw new FinalizationError("Report generation failed");await recordDomainChange(tx,{eventType:"engagement.report.generated",aggregateType:"engagement",aggregateId:engagementId,action:"engagement.report.generate",entityType:"report",entityId:row.id,payload:{version,reportType},newValues:{status:"PENDING"}});return {...row,version};}

export async function approveReport(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.reportApprove);const reportId=uuid(input.reportId,"reportId");const report=(await tx.db.execute<{engagement_id:string;generated_by:string;status:string}>(sql`select engagement_id,generated_by,status::text from reports where id=${reportId}::uuid`)).rows[0];if(!report)throw new FinalizationError("Report not found");if(report.generated_by===tx.principal.userId)throw new FinalizationError("Report generator cannot approve their own report");await tx.db.execute(sql`update reports set status='APPROVED',approved_by=${tx.principal.userId}::uuid,approved_at=now(),updated_at=now() where id=${reportId}::uuid`);await recordDomainChange(tx,{eventType:"engagement.report.approved",aggregateType:"engagement",aggregateId:report.engagement_id,action:"engagement.report.approve",entityType:"report",entityId:reportId,payload:{},newValues:{status:"APPROVED"}});return {id:reportId};}

export async function closeEngagement(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.engagementClose);const engagementId=uuid(input.engagementId,"engagementId");if((await engagementStatus(tx,engagementId))!=="REVIEW")throw new FinalizationError("Final assurance closure requires REVIEW status");await tx.db.execute(sql`update engagements set status='CLOSED',updated_at=now() where id=${engagementId}::uuid and organization_id=${tx.context.organizationId}::uuid`);await recordDomainChange(tx,{eventType:"engagement.closed",aggregateType:"engagement",aggregateId:engagementId,action:"engagement.close",entityType:"engagement",entityId:engagementId,payload:{},newValues:{status:"CLOSED"}});return {id:engagementId,status:"CLOSED"};}

export async function freezeEngagement(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.engagementFreeze);const engagementId=uuid(input.engagementId,"engagementId"),freezeReason=text(input.freezeReason,"freezeReason");if((await engagementStatus(tx,engagementId))!=="CLOSED")throw new FinalizationError("Only CLOSED engagements may be frozen");const snapshot=(await tx.db.execute<{engagement_id:string;workpapers:string;findings:string;reports:string;signoffs:string}>(sql`select ${engagementId}::text engagement_id,(select count(*)::text from workpapers where engagement_id=${engagementId}::uuid) workpapers,(select count(*)::text from findings where engagement_id=${engagementId}::uuid) findings,(select count(*)::text from reports where engagement_id=${engagementId}::uuid) reports,(select count(*)::text from signoffs where engagement_id=${engagementId}::uuid) signoffs`)).rows[0];const snapshotHash=createHash("sha256").update(JSON.stringify(snapshot)).digest("hex");const version=Number((await tx.db.execute<{version:number}>(sql`select coalesce(max(version),0)+1 as version from audit_freezes where engagement_id=${engagementId}::uuid`)).rows[0]?.version??1);const r=await tx.db.execute<{id:string}>(sql`insert into audit_freezes(engagement_id,version,frozen_by,freeze_reason,snapshot_hash) values(${engagementId}::uuid,${version},${tx.principal.userId}::uuid,${freezeReason},${snapshotHash}) returning id`);const row=r.rows[0];if(!row)throw new FinalizationError("Audit freeze failed");await recordDomainChange(tx,{eventType:"engagement.audit_frozen",aggregateType:"engagement",aggregateId:engagementId,action:"engagement.freeze",entityType:"audit_freeze",entityId:row.id,payload:{version},newValues:{snapshotHash,freezeReason}});return {...row,version,snapshotHash};}

export async function finalizationReadiness(tx:AuthorizedTenantTransaction,engagementId:string){requirePermission(tx.membership.role,permissions.engagementRead);const r=await tx.db.execute<{review_ready:boolean;signoff_ready:boolean;report_ready:boolean;closure_ready:boolean;freeze_ready:boolean}>(sql`select engagement_review_ready(${engagementId}::uuid) review_ready,engagement_signoff_ready(${engagementId}::uuid) signoff_ready,engagement_report_ready(${engagementId}::uuid) report_ready,engagement_closure_ready(${engagementId}::uuid) closure_ready,engagement_freeze_ready(${engagementId}::uuid) freeze_ready`);return r.rows[0]??{review_ready:false,signoff_ready:false,report_ready:false,closure_ready:false,freeze_ready:false};}
