import "server-only";

import { sql } from "drizzle-orm";
import type { AuthorizedTenantTransaction } from "@/auth/authorize";
import { permissions, requirePermission } from "@/auth/rbac";
import { recordDomainChange } from "@/domain/record-event";

export class OutcomeValidationError extends Error { constructor(message:string){super(message);this.name="OutcomeValidationError";} }
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function uuid(v:unknown,n:string){if(typeof v!=="string"||!UUID.test(v))throw new OutcomeValidationError(`${n} must be a UUID`);return v;}
function text(v:unknown,n:string,max=20000){if(typeof v!=="string"||!v.trim())throw new OutcomeValidationError(`${n} is required`);const x=v.trim();if(x.length>max)throw new OutcomeValidationError(`${n} must not exceed ${max} characters`);return x;}
function number(v:unknown,n:string){const x=Number(v);if(!Number.isFinite(x))throw new OutcomeValidationError(`${n} must be numeric`);return x;}
async function requireExecutionState(tx:AuthorizedTenantTransaction,engagementId:string){const r=await tx.db.execute<{status:string}>(sql`select status::text from engagements where id=${engagementId}::uuid and organization_id=${tx.context.organizationId}::uuid`);if(!r.rows[0])throw new OutcomeValidationError("Engagement not found");if(!["TESTING","REVIEW"].includes(r.rows[0].status))throw new OutcomeValidationError(`Outcome management is not allowed in ${r.rows[0].status}`);}

export async function createException(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.findingCreate);const testResultId=uuid(input.testResultId,"testResultId");const row=(await tx.db.execute<{engagement_id:string;workpaper_id:string}>(sql`select w.engagement_id,tr.workpaper_id from test_results tr join workpapers w on w.id=tr.workpaper_id where tr.id=${testResultId}::uuid and w.organization_id=${tx.context.organizationId}::uuid`)).rows[0];if(!row)throw new OutcomeValidationError("Test result not found");await requireExecutionState(tx,row.engagement_id);const description=text(input.description,"description"),severity=text(input.severity,"severity",100);const r=await tx.db.execute<{id:string}>(sql`insert into exceptions(organization_id,engagement_id,workpaper_id,test_result_id,description,severity,created_by) values(${tx.context.organizationId}::uuid,${row.engagement_id}::uuid,${row.workpaper_id}::uuid,${testResultId}::uuid,${description},${severity},${tx.principal.userId}::uuid) returning id`);const created=r.rows[0];if(!created)throw new OutcomeValidationError("Exception write failed");await recordDomainChange(tx,{eventType:"engagement.exception.created",aggregateType:"engagement",aggregateId:row.engagement_id,action:"engagement.exception.create",entityType:"exception",entityId:created.id,payload:{testResultId},newValues:{description,severity}});return created;}

export async function createObservation(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.findingCreate);const testResultId=uuid(input.testResultId,"testResultId");const row=(await tx.db.execute<{engagement_id:string;workpaper_id:string}>(sql`select w.engagement_id,tr.workpaper_id from test_results tr join workpapers w on w.id=tr.workpaper_id where tr.id=${testResultId}::uuid and w.organization_id=${tx.context.organizationId}::uuid`)).rows[0];if(!row)throw new OutcomeValidationError("Test result not found");await requireExecutionState(tx,row.engagement_id);const observationType=text(input.observationType,"observationType",100),description=text(input.description,"description"),significance=typeof input.significance==="string"&&input.significance.trim()?input.significance.trim():null;const r=await tx.db.execute<{id:string}>(sql`insert into observations(organization_id,engagement_id,workpaper_id,test_result_id,observation_type,description,significance,created_by) values(${tx.context.organizationId}::uuid,${row.engagement_id}::uuid,${row.workpaper_id}::uuid,${testResultId}::uuid,${observationType}::observation_type,${description},${significance},${tx.principal.userId}::uuid) returning id`);const created=r.rows[0];if(!created)throw new OutcomeValidationError("Observation write failed");await recordDomainChange(tx,{eventType:"engagement.observation.created",aggregateType:"engagement",aggregateId:row.engagement_id,action:"engagement.observation.create",entityType:"observation",entityId:created.id,payload:{testResultId},newValues:{observationType,description,significance}});return created;}

export async function createFinding(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.findingCreate);const sourceType=input.sourceType==="EXCEPTION"?"EXCEPTION":input.sourceType==="OBSERVATION"?"OBSERVATION":null;if(!sourceType)throw new OutcomeValidationError("sourceType must be EXCEPTION or OBSERVATION");const sourceId=uuid(input.sourceId,"sourceId");const source=sourceType==="EXCEPTION"?(await tx.db.execute<{engagement_id:string}>(sql`select engagement_id from exceptions where id=${sourceId}::uuid and organization_id=${tx.context.organizationId}::uuid`)).rows[0]:(await tx.db.execute<{engagement_id:string}>(sql`select engagement_id from observations where id=${sourceId}::uuid and organization_id=${tx.context.organizationId}::uuid`)).rows[0];if(!source)throw new OutcomeValidationError("Finding source not found");await requireExecutionState(tx,source.engagement_id);const title=text(input.title,"title",500),description=text(input.description,"description"),findingType=text(input.findingType,"findingType",100);const exceptionId=sourceType==="EXCEPTION"?sourceId:null,observationId=sourceType==="OBSERVATION"?sourceId:null;const r=await tx.db.execute<{id:string}>(sql`insert into findings(organization_id,engagement_id,exception_id,observation_id,title,description,finding_type,created_by) values(${tx.context.organizationId}::uuid,${source.engagement_id}::uuid,${exceptionId}::uuid,${observationId}::uuid,${title},${description},${findingType},${tx.principal.userId}::uuid) returning id`);const created=r.rows[0];if(!created)throw new OutcomeValidationError("Finding write failed");await recordDomainChange(tx,{eventType:"engagement.finding.created",aggregateType:"engagement",aggregateId:source.engagement_id,action:"engagement.finding.create",entityType:"finding",entityId:created.id,payload:{sourceType,sourceId},newValues:{title,findingType}});return created;}

export async function assessFindingRisk(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.findingUpdate);const findingId=uuid(input.findingId,"findingId");const finding=(await tx.db.execute<{engagement_id:string}>(sql`select engagement_id from findings where id=${findingId}::uuid and organization_id=${tx.context.organizationId}::uuid`)).rows[0];if(!finding)throw new OutcomeValidationError("Finding not found");await requireExecutionState(tx,finding.engagement_id);const likelihood=number(input.likelihood,"likelihood"),impact=number(input.impact,"impact"),methodVersion=typeof input.methodVersion==="string"&&input.methodVersion.trim()?input.methodVersion.trim():"DPM-RISK-MULTIPLICATIVE-1",rationale=text(input.rationale,"rationale");const score=(await tx.db.execute<{score:string}>(sql`select calculate_risk_score(${methodVersion},${likelihood},${impact})::text as score`)).rows[0]?.score;if(!score)throw new OutcomeValidationError("Risk score calculation failed");const r=await tx.db.execute<{id:string}>(sql`insert into risks(organization_id,engagement_id,finding_id,likelihood,impact,score,method_version,rationale,assessed_by) values(${tx.context.organizationId}::uuid,${finding.engagement_id}::uuid,${findingId}::uuid,${likelihood},${impact},${score},${methodVersion},${rationale},${tx.principal.userId}::uuid) returning id`);const created=r.rows[0];if(!created)throw new OutcomeValidationError("Risk assessment write failed");await recordDomainChange(tx,{eventType:"engagement.risk.assessed",aggregateType:"engagement",aggregateId:finding.engagement_id,action:"engagement.risk.assess",entityType:"risk",entityId:created.id,payload:{findingId,methodVersion},newValues:{likelihood,impact,score}});return {...created,score};}

export async function createRemediation(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.findingUpdate);const findingId=uuid(input.findingId,"findingId");const finding=(await tx.db.execute<{engagement_id:string}>(sql`select engagement_id from findings where id=${findingId}::uuid and organization_id=${tx.context.organizationId}::uuid`)).rows[0];if(!finding)throw new OutcomeValidationError("Finding not found");const plan=text(input.plan,"plan"),ownerUserId=input.ownerUserId?uuid(input.ownerUserId,"ownerUserId"):null,targetDate=typeof input.targetDate==="string"&&input.targetDate?input.targetDate:null;const r=await tx.db.execute<{id:string}>(sql`insert into remediations(organization_id,engagement_id,finding_id,owner_user_id,plan,target_date) values(${tx.context.organizationId}::uuid,${finding.engagement_id}::uuid,${findingId}::uuid,${ownerUserId}::uuid,${plan},${targetDate}::date) returning id`);const created=r.rows[0];if(!created)throw new OutcomeValidationError("Remediation write failed");return created;}

export async function completeRemediation(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.findingUpdate);const remediationId=uuid(input.remediationId,"remediationId");const r=await tx.db.execute<{finding_id:string}>(sql`update remediations set status='COMPLETED',completed_at=now(),completed_by=${tx.principal.userId}::uuid,updated_at=now() where id=${remediationId}::uuid and organization_id=${tx.context.organizationId}::uuid returning finding_id`);if(!r.rows[0])throw new OutcomeValidationError("Remediation not found");return {id:remediationId};}

export async function createRiskAcceptance(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.findingUpdate);const findingId=uuid(input.findingId,"findingId"),rationale=text(input.rationale,"rationale");const expiresAt=new Date(String(input.expiresAt??"")),reviewDueAt=new Date(String(input.reviewDueAt??""));if(Number.isNaN(expiresAt.getTime())||Number.isNaN(reviewDueAt.getTime()))throw new OutcomeValidationError("Risk acceptance dates are invalid");const finding=(await tx.db.execute<{engagement_id:string}>(sql`select engagement_id from findings where id=${findingId}::uuid and organization_id=${tx.context.organizationId}::uuid`)).rows[0];if(!finding)throw new OutcomeValidationError("Finding not found");const r=await tx.db.execute<{id:string}>(sql`insert into risk_acceptances(organization_id,engagement_id,finding_id,accepted_by,rationale,expires_at,review_due_at) values(${tx.context.organizationId}::uuid,${finding.engagement_id}::uuid,${findingId}::uuid,${tx.principal.userId}::uuid,${rationale},${expiresAt},${reviewDueAt}) returning id`);const created=r.rows[0];if(!created)throw new OutcomeValidationError("Risk acceptance write failed");return created;}

export async function approveRiskAcceptance(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.findingClose);const riskAcceptanceId=uuid(input.riskAcceptanceId,"riskAcceptanceId");const row=(await tx.db.execute<{accepted_by:string}>(sql`select accepted_by from risk_acceptances where id=${riskAcceptanceId}::uuid and organization_id=${tx.context.organizationId}::uuid`)).rows[0];if(!row)throw new OutcomeValidationError("Risk acceptance not found");if(row.accepted_by===tx.principal.userId)throw new OutcomeValidationError("Risk acceptance creator cannot approve their own acceptance");await tx.db.execute(sql`update risk_acceptances set approval_status='APPROVED',approved_by=${tx.principal.userId}::uuid,approved_at=now(),status='COMPLETED' where id=${riskAcceptanceId}::uuid`);return {id:riskAcceptanceId};}

export async function recordRetest(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.findingUpdate);const findingId=uuid(input.findingId,"findingId"),remediationId=input.remediationId?uuid(input.remediationId,"remediationId"):null,evidenceId=input.evidenceId?uuid(input.evidenceId,"evidenceId"):null,result=text(input.result,"result",30),conclusion=text(input.conclusion,"conclusion");const finding=(await tx.db.execute<{engagement_id:string}>(sql`select engagement_id from findings where id=${findingId}::uuid and organization_id=${tx.context.organizationId}::uuid`)).rows[0];if(!finding)throw new OutcomeValidationError("Finding not found");const r=await tx.db.execute<{id:string}>(sql`insert into retests(organization_id,engagement_id,finding_id,remediation_id,result,evidence_id,tested_by,conclusion) values(${tx.context.organizationId}::uuid,${finding.engagement_id}::uuid,${findingId}::uuid,${remediationId}::uuid,${result}::test_result_status,${evidenceId}::uuid,${tx.principal.userId}::uuid,${conclusion}) returning id`);const created=r.rows[0];if(!created)throw new OutcomeValidationError("Retest write failed");return created;}

export async function closeFinding(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.findingClose);const findingId=uuid(input.findingId,"findingId");const r=await tx.db.execute<{engagement_id:string}>(sql`update findings set status='CLOSED',updated_at=now() where id=${findingId}::uuid and organization_id=${tx.context.organizationId}::uuid returning engagement_id`);if(!r.rows[0])throw new OutcomeValidationError("Finding not found");await recordDomainChange(tx,{eventType:"engagement.finding.closed",aggregateType:"engagement",aggregateId:r.rows[0].engagement_id,action:"engagement.finding.close",entityType:"finding",entityId:findingId,payload:{},newValues:{status:"CLOSED"}});return {id:findingId};}
