import "server-only";

import { sql } from "drizzle-orm";
import type { AuthorizedTenantTransaction } from "@/auth/authorize";
import { permissions, requirePermission } from "@/auth/rbac";
import { recordDomainChange } from "@/domain/record-event";

export class PostAuditError extends Error { constructor(message:string){super(message);this.name="PostAuditError";} }
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function uuid(v:unknown,n:string){if(typeof v!=="string"||!UUID.test(v))throw new PostAuditError(`${n} must be a UUID`);return v;}
function text(v:unknown,n:string,max=20000){if(typeof v!=="string"||!v.trim())throw new PostAuditError(`${n} is required`);const x=v.trim();if(x.length>max)throw new PostAuditError(`${n} must not exceed ${max} characters`);return x;}

export async function archiveEngagement(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.engagementFreeze);const engagementId=uuid(input.engagementId,"engagementId"),archiveReason=text(input.archiveReason,"archiveReason");const retentionUntil=typeof input.retentionUntil==="string"&&input.retentionUntil?new Date(input.retentionUntil):null;if(retentionUntil&&Number.isNaN(retentionUntil.getTime()))throw new PostAuditError("retentionUntil must be a valid timestamp");const freeze=(await tx.db.execute<{id:string}>(sql`select id from audit_freezes where engagement_id=${engagementId}::uuid order by version desc limit 1`)).rows[0];if(!freeze)throw new PostAuditError("Engagement must be frozen before archive");const r=await tx.db.execute<{id:string}>(sql`insert into engagement_archives(organization_id,engagement_id,audit_freeze_id,archived_by,retention_until,archive_reason) values(${tx.context.organizationId}::uuid,${engagementId}::uuid,${freeze.id}::uuid,${tx.principal.userId}::uuid,${retentionUntil},${archiveReason}) returning id`);const row=r.rows[0];if(!row)throw new PostAuditError("Archive failed");await recordDomainChange(tx,{eventType:"engagement.archived",aggregateType:"engagement",aggregateId:engagementId,action:"engagement.archive",entityType:"engagement_archive",entityId:row.id,payload:{auditFreezeId:freeze.id},newValues:{archiveReason,retentionUntil:retentionUntil?.toISOString()??null}});return row;}

export async function createMonitoringProgram(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.engagementUpdate);const baselineEngagementId=uuid(input.baselineEngagementId,"baselineEngagementId"),name=text(input.name,"name",500),cadenceDays=Number(input.cadenceDays);if(!Number.isSafeInteger(cadenceDays)||cadenceDays<1)throw new PostAuditError("cadenceDays must be a positive integer");const nextDueAt=new Date(String(input.nextDueAt??""));if(Number.isNaN(nextDueAt.getTime()))throw new PostAuditError("nextDueAt must be a valid timestamp");const r=await tx.db.execute<{id:string}>(sql`insert into monitoring_programs(organization_id,baseline_engagement_id,name,cadence_days,next_due_at,created_by) values(${tx.context.organizationId}::uuid,${baselineEngagementId}::uuid,${name},${cadenceDays},${nextDueAt},${tx.principal.userId}::uuid) returning id`);const row=r.rows[0];if(!row)throw new PostAuditError("Monitoring program write failed");await recordDomainChange(tx,{eventType:"engagement.monitoring_program.created",aggregateType:"engagement",aggregateId:baselineEngagementId,action:"engagement.monitoring_program.create",entityType:"monitoring_program",entityId:row.id,payload:{baselineEngagementId},newValues:{name,cadenceDays,nextDueAt:nextDueAt.toISOString()}});return row;}

export async function recordMonitoringCheck(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.engagementUpdate);const monitoringProgramId=uuid(input.monitoringProgramId,"monitoringProgramId"),result=text(input.result,"result",50),summary=text(input.summary,"summary"),evidenceId=input.evidenceId?uuid(input.evidenceId,"evidenceId"):null;if(!["CLEAR","CHANGE_DETECTED","INSUFFICIENT_EVIDENCE"].includes(result))throw new PostAuditError("Invalid monitoring result");const program=(await tx.db.execute<{baseline_engagement_id:string;cadence_days:number}>(sql`select baseline_engagement_id,cadence_days from monitoring_programs where id=${monitoringProgramId}::uuid and organization_id=${tx.context.organizationId}::uuid for update`)).rows[0];if(!program)throw new PostAuditError("Monitoring program not found");const r=await tx.db.execute<{id:string}>(sql`insert into monitoring_checks(organization_id,monitoring_program_id,result,summary,checked_by,evidence_id) values(${tx.context.organizationId}::uuid,${monitoringProgramId}::uuid,${result}::monitoring_result,${summary},${tx.principal.userId}::uuid,${evidenceId}::uuid) returning id`);const row=r.rows[0];if(!row)throw new PostAuditError("Monitoring check write failed");const nextDueAt=new Date(Date.now()+program.cadence_days*86_400_000);await tx.db.execute(sql`update monitoring_programs set next_due_at=${nextDueAt},updated_at=now() where id=${monitoringProgramId}::uuid`);await recordDomainChange(tx,{eventType:"engagement.monitoring_check.recorded",aggregateType:"engagement",aggregateId:program.baseline_engagement_id,action:"engagement.monitoring_check.record",entityType:"monitoring_check",entityId:row.id,payload:{monitoringProgramId,evidenceId},newValues:{result,summary,nextDueAt:nextDueAt.toISOString()}});return {...row,nextDueAt:nextDueAt.toISOString()};}

export async function createChangeEvent(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){requirePermission(tx.membership.role,permissions.engagementUpdate);const baselineEngagementId=uuid(input.baselineEngagementId,"baselineEngagementId"),monitoringCheckId=input.monitoringCheckId?uuid(input.monitoringCheckId,"monitoringCheckId"):null,evidenceId=input.evidenceId?uuid(input.evidenceId,"evidenceId"):null;if(!monitoringCheckId&&!evidenceId)throw new PostAuditError("A monitoring check or evidence reference is required");const changeType=text(input.changeType,"changeType",200),description=text(input.description,"description");const r=await tx.db.execute<{id:string}>(sql`insert into change_events(organization_id,baseline_engagement_id,monitoring_check_id,evidence_id,change_type,description,detected_by) values(${tx.context.organizationId}::uuid,${baselineEngagementId}::uuid,${monitoringCheckId}::uuid,${evidenceId}::uuid,${changeType},${description},${tx.principal.userId}::uuid) returning id`);const row=r.rows[0];if(!row)throw new PostAuditError("Change event write failed");await recordDomainChange(tx,{eventType:"engagement.change.recorded",aggregateType:"engagement",aggregateId:baselineEngagementId,action:"engagement.change.record",entityType:"change_event",entityId:row.id,payload:{monitoringCheckId,evidenceId},newValues:{changeType,description,status:"OPEN"}});return row;}

export async function reassessChange(tx:AuthorizedTenantTransaction,input:Record<string,unknown>){const changeEventId=uuid(input.changeEventId,"changeEventId"),decision=text(input.decision,"decision",50),rationale=text(input.rationale,"rationale");if(!["NO_ACTION","UPDATE_MONITORING","NEW_ENGAGEMENT"].includes(decision))throw new PostAuditError("Invalid reassessment decision");requirePermission(tx.membership.role,decision==="NEW_ENGAGEMENT"?permissions.engagementCreate:permissions.engagementUpdate);const change=(await tx.db.execute<{baseline_engagement_id:string;client_id:string;name:string;status:string}>(sql`select ce.baseline_engagement_id,e.client_id,e.name,ce.status::text from change_events ce join engagements e on e.id=ce.baseline_engagement_id where ce.id=${changeEventId}::uuid and ce.organization_id=${tx.context.organizationId}::uuid for update of ce`)).rows[0];if(!change)throw new PostAuditError("Change event not found");if(change.status!=="OPEN")throw new PostAuditError(`Change event cannot be reassessed from status ${change.status}`);let successorId:string|null=null;if(decision==="NEW_ENGAGEMENT"){const name=typeof input.successorName==="string"&&input.successorName.trim()?input.successorName.trim():`${change.name} — reassessment`;const successor=(await tx.db.execute<{id:string}>(sql`insert into engagements(organization_id,client_id,name,description,status,created_by) values(${tx.context.organizationId}::uuid,${change.client_id}::uuid,${name},${`Successor reassessment for archived baseline ${change.baseline_engagement_id}`},'PLANNING',${tx.principal.userId}::uuid) returning id`)).rows[0];if(!successor)throw new PostAuditError("Successor engagement creation failed");successorId=successor.id;}
 const r=await tx.db.execute<{id:string}>(sql`insert into reassessments(organization_id,baseline_engagement_id,change_event_id,decision,rationale,assessed_by,successor_engagement_id) values(${tx.context.organizationId}::uuid,${change.baseline_engagement_id}::uuid,${changeEventId}::uuid,${decision}::reassessment_decision,${rationale},${tx.principal.userId}::uuid,${successorId}::uuid) returning id`);const row=r.rows[0];if(!row)throw new PostAuditError("Reassessment write failed");await tx.db.execute(sql`update change_events set status='COMPLETED' where id=${changeEventId}::uuid and organization_id=${tx.context.organizationId}::uuid`);await recordDomainChange(tx,{eventType:"engagement.change.reassessed",aggregateType:"engagement",aggregateId:change.baseline_engagement_id,action:"engagement.reassess",entityType:"reassessment",entityId:row.id,payload:{changeEventId},newValues:{decision,successorEngagementId:successorId,changeStatus:"COMPLETED"}});return {...row,successorEngagementId:successorId};}
