"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

type RequestItem={id:string;title:string;description:string|null;status:string;dueAt:string|null;expectedEvidence:string|null;engagementName:string;clientName:string;responses:number};
export function ClientPbcClient({organizationId,requests}:{organizationId:string;requests:RequestItem[]}){
 const router=useRouter();const[msg,setMsg]=useState<string|null>(null);const[busy,setBusy]=useState(false);
 async function post(body:Record<string,unknown>){const r=await fetch(`/api/organizations/${organizationId}/client-portal`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw new Error(b.message??"Client portal action rejected");return b.result;}
 async function respond(pbcRequestId:string,responseText:string){setBusy(true);setMsg(null);try{await post({pbcRequestId,responseText});setMsg("Response submitted and recorded in the audit trail.");router.refresh();}catch(error){setMsg(error instanceof Error?error.message:"Response rejected");}finally{setBusy(false);}}
 async function uploadEvidence(pbcRequestId:string,form:HTMLFormElement){setBusy(true);setMsg(null);try{const d=new FormData(form);const file=d.get("file");if(!(file instanceof File))throw new Error("Select an evidence file");const intent=await post({action:"create_evidence_upload_intent",input:{pbcRequestId,filename:file.name,mimeType:file.type||"application/octet-stream",sizeBytes:file.size}});const uploaded=await fetch(intent.uploadUrl,{method:"PUT",headers:intent.requiredHeaders,body:file});if(!uploaded.ok)throw new Error(`Private evidence upload failed (${uploaded.status})`);const finalized=await post({action:"finalize_evidence_upload",input:{intentId:intent.intentId,sourceDescription:d.get("sourceDescription")||undefined,acquiredAt:d.get("acquiredAt")||undefined,periodStart:d.get("periodStart")||undefined,periodEnd:d.get("periodEnd")||undefined}});setMsg(`Evidence submitted securely. SHA-256 ${String(finalized.sha256).slice(0,12)}… Auditor acceptance is still required.`);form.reset();router.refresh();}catch(error){setMsg(error instanceof Error?error.message:"Evidence upload rejected");}finally{setBusy(false);}}
 return <>{msg&&<p className="form-message">{msg}</p>}<div className="signal-list">{requests.map(request=><article className="signal-card" key={request.id}><div className="signal-meta"><span>{request.status}</span><span>{request.dueAt?`Due ${new Date(request.dueAt).toLocaleString()}`:"No due date"}</span></div><h3>{request.title}</h3><p>{request.description??"No additional description"}</p><p><strong>Expected evidence:</strong> {request.expectedEvidence??"Not specified"}</p><small>{request.clientName} · {request.engagementName} · {request.responses} response(s)</small><form className="auth-form" onSubmit={e=>{e.preventDefault();void respond(request.id,String(new FormData(e.currentTarget).get("responseText")??""));}}><textarea name="responseText" required placeholder="Response, availability details, questions, or evidence context"/><button disabled={busy||["CLOSED","CANCELLED"].includes(request.status)}>Submit response</button></form><form className="auth-form" onSubmit={e=>{e.preventDefault();void uploadEvidence(request.id,e.currentTarget);}}><h4>Submit requested evidence</h4><p className="lede compact">Files are uploaded to private storage. DPM-Assure retrieves the uploaded object server-side and computes SHA-256 before registering it as evidence. Uploading does not by itself satisfy the request or pass the Evidence Gate.</p><input name="file" type="file" required/><textarea name="sourceDescription" placeholder="Evidence source/provenance (optional; defaults to client portal submission)"/><label>Acquired at<input name="acquiredAt" type="datetime-local"/></label><div className="form-grid"><label>Period start<input name="periodStart" type="date"/></label><label>Period end<input name="periodEnd" type="date"/></label></div><button disabled={busy||["CLOSED","CANCELLED"].includes(request.status)}>Upload evidence privately</button></form></article>)}</div></>;
}
