import Link from "next/link";
import { redirect } from "next/navigation";
import { getCurrentUserContext } from "@/auth/current-user-context";
import { withAuthorizedTenantTransaction } from "@/auth/authorize";
import { permissions } from "@/auth/rbac";
import { listClientPortalRequests } from "@/domain/client-portal/service";
import { ClientPbcClient } from "./ClientPbcClient";

export const dynamic="force-dynamic";
type PageProps={params:Promise<{organizationId:string}>};
export default async function ClientPortalPage({params}:PageProps){const{organizationId}=await params;const current=await getCurrentUserContext();if(!current)redirect("/login");const membership=current.memberships.find(x=>x.organizationId===organizationId);if(!membership)redirect("/dashboard");if(membership.role!=="CLIENT")redirect("/dashboard");const requests=await withAuthorizedTenantTransaction({principal:current.principal,organizationId,requestId:crypto.randomUUID(),permission:permissions.clientPortalRead},listClientPortalRequests);const mapped=requests.length>0?requests[0]?.client_name:null;return <main className="dashboard-shell"><Link className="back-link" href="/dashboard">← Dashboard</Link><header className="dashboard-header"><div><p className="eyebrow">Client portal</p><h1>Evidence requests</h1><p className="lede compact">{mapped??membership.organizationName} · only requests explicitly assigned to your verified client identity are shown.</p></div><span className="role-badge">CLIENT</span></header><section className="monitoring-summary"><article><strong>{requests.length}</strong><span>Assigned requests</span></article><article><strong>{requests.filter(x=>x.status==="OPEN"||x.status==="IN_PROGRESS").length}</strong><span>Active</span></article><article><strong>{requests.filter(x=>x.due_at&&new Date(x.due_at)<new Date()&&!['COMPLETED','CLOSED','CANCELLED'].includes(x.status)).length}</strong><span>Overdue</span></article></section><section className="workspace-panel"><div className="section-heading"><div><p className="eyebrow">Provided by Client</p><h2>PBC requests</h2></div></div>{requests.length===0?<div className="empty-state"><strong>No assigned requests.</strong><p>Organization membership alone does not expose engagements or audit records. An auditor must explicitly assign a request to your mapped client identity.</p></div>:<ClientPbcClient organizationId={organizationId} requests={requests.map(x=>({id:x.id,title:x.title,description:x.description,status:x.status,dueAt:x.due_at,expectedEvidence:x.expected_evidence,engagementName:x.engagement_name,clientName:x.client_name,responses:Number(x.responses)}))}/>}</section></main>;}
