"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
type Option={id:string;label:string};
export function PostAuditClient({organizationId,engagementId,status,frozen,archived,programs,checks,changes,evidence}:{organizationId:string;engagementId:string;status:string;frozen:boolean;archived:boolean;programs:Option[];checks:Option[];changes:Option[];evidence:Option[]}){const router=useRouter();const[msg,setMsg]=useState<string|null>(null);const[busy,setBusy]=useState(false);async function send(action:string,payload:Record<string,unknown>={}){setBusy(true);setMsg(null);const r=await fetch(`/api/organizations/${organizationId}/engagements/${engagementId}/postaudit`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,...payload})});const b=await r.json();setBusy(false);if(!r.ok){setMsg(b.message??"Action rejected");return;}setMsg(b.result?.successorEngagementId?`Successor engagement created: ${b.result.successorEngagementId}`:"Saved.");router.refresh();}
 return <section className="workspace-panel"><div className="section-heading"><div><p className="eyebrow">Post-audit actions</p><h2>Archive, monitoring and reassessment</h2></div></div>{msg&&<p className="form-message">{msg}</p>}<div className="organization-grid">
 <form className="organization-card auth-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void send("archive",{archiveReason:d.get("archiveReason"),retentionUntil:d.get("retentionUntil")||null});}}><h3>Archive frozen baseline</h3><textarea name="archiveReason" required placeholder="Archive reason"/><label>Retention until<input name="retentionUntil" type="datetime-local"/></label><button disabled={busy||status!=="CLOSED"||!frozen||archived}>Archive engagement</button></form>
 <form className="organization-card auth-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void send("create_program",{name:d.get("name"),cadenceDays:d.get("cadenceDays"),nextDueAt:d.get("nextDueAt")});}}><h3>Create monitoring program</h3><input name="name" required placeholder="Program name"/><input name="cadenceDays" type="number" min="1" required placeholder="Cadence days"/><label>Next due<input name="nextDueAt" type="datetime-local" required/></label><button disabled={busy||!archived}>Create program</button></form>
 <form className="organization-card auth-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void send("record_check",{monitoringProgramId:d.get("programId"),result:d.get("result"),summary:d.get("summary"),evidenceId:d.get("evidenceId")||null});}}><h3>Record monitoring check</h3><select name="programId" required defaultValue=""><option value="" disabled>Monitoring program</option>{programs.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select name="result" defaultValue="CLEAR"><option>CLEAR</option><option>CHANGE_DETECTED</option><option>INSUFFICIENT_EVIDENCE</option></select><select name="evidenceId" defaultValue=""><option value="">No evidence</option>{evidence.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><textarea name="summary" required placeholder="Check summary"/><button disabled={busy||programs.length===0}>Record check</button></form>
 <form className="organization-card auth-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void send("create_change",{monitoringCheckId:d.get("checkId")||null,evidenceId:d.get("evidenceId")||null,changeType:d.get("changeType"),description:d.get("description")});}}><h3>Create change event</h3><select name="checkId" defaultValue=""><option value="">No monitoring check</option>{checks.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select name="evidenceId" defaultValue=""><option value="">No evidence</option>{evidence.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><input name="changeType" required placeholder="Change type"/><textarea name="description" required placeholder="Description"/><button disabled={busy}>Record change</button></form>
 <form className="organization-card auth-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void send("reassess",{changeEventId:d.get("changeEventId"),decision:d.get("decision"),rationale:d.get("rationale"),successorName:d.get("successorName")||null});}}><h3>Reassess change</h3><select name="changeEventId" required defaultValue=""><option value="" disabled>Open change</option>{changes.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select name="decision" defaultValue="NO_ACTION"><option>NO_ACTION</option><option>UPDATE_MONITORING</option><option>NEW_ENGAGEMENT</option></select><textarea name="rationale" required placeholder="Reassessment rationale"/><input name="successorName" placeholder="Successor engagement name (optional)"/><button disabled={busy||changes.length===0}>Record reassessment</button></form>
 </div></section>;}
