"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

type Option={id:string;label:string};
type GateValue="PASS"|"FAIL"|"INSUFFICIENT_EVIDENCE";
const gateValues:GateValue[]=["PASS","FAIL","INSUFFICIENT_EVIDENCE"];

export function EvidenceClient({organizationId,engagementId,workpapers,procedures,pbcRequests,evidence,gates}:{organizationId:string;engagementId:string;workpapers:Option[];procedures:Array<Option&{workpaperId:string}>;pbcRequests:Option[];evidence:Option[];gates:Option[]}){
 const router=useRouter();const[msg,setMsg]=useState<string|null>(null);const[busy,setBusy]=useState(false);
 async function send(action:string,payload:Record<string,unknown>){setBusy(true);setMsg(null);const r=await fetch(`/api/organizations/${organizationId}/engagements/${engagementId}/evidence`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,...payload})});const b=await r.json();setBusy(false);if(!r.ok){setMsg(b.message??"Evidence action rejected");return;}setMsg(b.result?.overall?`Evidence Gate result: ${b.result.overall}`:"Saved.");router.refresh();}
 async function storage(action:string,input:Record<string,unknown>){const r=await fetch(`/api/organizations/${organizationId}/engagements/${engagementId}/evidence/storage`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,input})});const b=await r.json();if(!r.ok)throw new Error(b.message??"Evidence storage action rejected");return b.result;}
 async function uploadFile(form:HTMLFormElement){setBusy(true);setMsg(null);try{const d=new FormData(form);const file=d.get("file");if(!(file instanceof File)||file.size<0)throw new Error("Select an evidence file");const intent=await storage("create_upload_intent",{workpaperId:d.get("workpaperId"),procedureId:d.get("procedureId")||undefined,pbcRequestId:d.get("pbcRequestId")||undefined,filename:file.name,mimeType:file.type||"application/octet-stream",sizeBytes:file.size});const put=await fetch(intent.uploadUrl,{method:"PUT",headers:intent.requiredHeaders,body:file});if(!put.ok)throw new Error(`Private object upload failed (${put.status})`);const finalized=await storage("finalize_upload",{intentId:intent.intentId,sourceDescription:d.get("sourceDescription"),acquiredAt:d.get("acquiredAt")||undefined,periodStart:d.get("periodStart")||undefined,periodEnd:d.get("periodEnd")||undefined});setMsg(`Evidence verified and registered. SHA-256 ${String(finalized.sha256).slice(0,12)}…`);form.reset();router.refresh();}catch(error){setMsg(error instanceof Error?error.message:"Evidence upload failed");}finally{setBusy(false);}}
 async function downloadEvidence(evidenceId:string){setBusy(true);setMsg(null);try{const signed=await storage("create_download",{evidenceId});window.location.assign(signed.url);}catch(error){setMsg(error instanceof Error?error.message:"Download rejected");}finally{setBusy(false);}}
 return <section className="workspace-panel"><div className="section-heading"><div><p className="eyebrow">Evidence actions</p><h2>Private storage, custody, Evidence Gate and testing</h2></div></div>{msg&&<p className="form-message">{msg}</p>}<div className="organization-grid">
 <form className="organization-card auth-form" onSubmit={e=>{e.preventDefault();void uploadFile(e.currentTarget);}}><h3>Upload private evidence</h3><p className="lede compact">The browser receives only a short-lived private upload URL. DPM-Assure retrieves the object and computes SHA-256 server-side before it becomes evidence.</p><select name="workpaperId" required defaultValue=""><option value="" disabled>Workpaper</option>{workpapers.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select name="procedureId" defaultValue=""><option value="">No procedure</option>{procedures.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select name="pbcRequestId" defaultValue=""><option value="">No PBC request</option>{pbcRequests.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><input name="file" type="file" required/><textarea name="sourceDescription" required placeholder="Evidence source/provenance"/><label>Acquired at<input name="acquiredAt" type="datetime-local"/></label><div className="form-grid"><label>Period start<input name="periodStart" type="date"/></label><label>Period end<input name="periodEnd" type="date"/></label></div><button disabled={busy}>Upload and verify evidence</button></form>
 <form className="organization-card auth-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void send("registerEvidence",{workpaperId:d.get("workpaperId"),procedureId:d.get("procedureId")||undefined,pbcRequestId:d.get("pbcRequestId")||undefined,filename:d.get("filename"),mimeType:d.get("mimeType"),sizeBytes:Number(d.get("sizeBytes")),storageKey:d.get("storageKey"),sha256:d.get("sha256"),sourceDescription:d.get("sourceDescription"),acquiredAt:d.get("acquiredAt")||undefined,periodStart:d.get("periodStart")||undefined,periodEnd:d.get("periodEnd")||undefined});}}><h3>Register external evidence reference</h3><p className="lede compact">For evidence retained in an approved external repository. The supplied digest remains an observed external-evidence assertion and should be independently verified at the Evidence Gate.</p><select name="workpaperId" required defaultValue=""><option value="" disabled>Workpaper</option>{workpapers.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select name="procedureId" defaultValue=""><option value="">No procedure</option>{procedures.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select name="pbcRequestId" defaultValue=""><option value="">No PBC request</option>{pbcRequests.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><input name="filename" required placeholder="Filename"/><input name="mimeType" required placeholder="MIME type"/><input name="sizeBytes" required type="number" min="0" placeholder="Size bytes"/><input name="storageKey" required placeholder="External repository key/reference"/><input name="sha256" required minLength={64} maxLength={64} placeholder="Observed SHA-256 hex digest"/><textarea name="sourceDescription" required placeholder="Evidence source/provenance"/><button disabled={busy}>Register external reference</button></form>
 <form className="organization-card auth-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void downloadEvidence(String(d.get("evidenceId")??""));}}><h3>Authorized evidence download</h3><p className="lede compact">Generates a short-lived private download URL only after tenant membership and evidence-read authorization.</p><select name="evidenceId" required defaultValue=""><option value="" disabled>Evidence</option>{evidence.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><button disabled={busy}>Download evidence</button></form>
 <form className="organization-card auth-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void send("recordCustodyEvent",{evidenceId:d.get("evidenceId"),eventType:d.get("eventType"),fromLocation:d.get("fromLocation")||null,toLocation:d.get("toLocation")||null,sha256:d.get("sha256"),notes:d.get("notes")||null});}}><h3>Append custody event</h3><select name="evidenceId" required defaultValue=""><option value="" disabled>Evidence</option>{evidence.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><input name="eventType" required placeholder="TRANSFERRED / VERIFIED / ACCESSED"/><input name="fromLocation" placeholder="From location"/><input name="toLocation" placeholder="To location"/><input name="sha256" required minLength={64} maxLength={64} placeholder="Observed SHA-256"/><textarea name="notes" placeholder="Custody notes"/><button disabled={busy}>Append custody event</button></form>
 <form className="organization-card auth-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);const gv=(n:string)=>(d.get(n)??"INSUFFICIENT_EVIDENCE") as GateValue;void send("evaluateGate",{evidenceId:d.get("evidenceId"),procedureId:d.get("procedureId")||null,gateVersion:d.get("gateVersion"),dimensions:{identity:gv("identity"),provenance:gv("provenance"),integrity:gv("integrity"),authorization:gv("authorization"),applicability:gv("applicability"),temporal:gv("temporal"),completeness:gv("completeness"),chainOfCustody:gv("chainOfCustody")},rationale:d.get("rationale")});}}><h3>Evaluate Evidence Gate</h3><select name="evidenceId" required defaultValue=""><option value="" disabled>Evidence</option>{evidence.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select name="procedureId" defaultValue=""><option value="">No procedure</option>{procedures.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><input name="gateVersion" defaultValue="DPM-EVIDENCE-GATE-1" required/>{["identity","provenance","integrity","authorization","applicability","temporal","completeness","chainOfCustody"].map(n=><label key={n}>{n.replaceAll(/([A-Z])/g," $1")}<select name={n} defaultValue="INSUFFICIENT_EVIDENCE">{gateValues.map(v=><option key={v}>{v}</option>)}</select></label>)}<textarea name="rationale" required placeholder="Evidence Gate rationale"/><button disabled={busy}>Evaluate gate</button></form>
 <form className="organization-card auth-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void send("recordTestResult",{workpaperId:d.get("workpaperId"),procedureId:d.get("procedureId"),evidenceGateResultId:d.get("evidenceGateResultId")||null,result:d.get("result"),exceptionSummary:d.get("exceptionSummary")||null,conclusion:d.get("conclusion")||null});}}><h3>Record test result</h3><select name="workpaperId" required defaultValue=""><option value="" disabled>Workpaper</option>{workpapers.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select name="procedureId" required defaultValue=""><option value="" disabled>Procedure</option>{procedures.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select name="evidenceGateResultId" defaultValue=""><option value="">No gate result</option>{gates.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select name="result" defaultValue="INSUFFICIENT_EVIDENCE"><option>PASS</option><option>FAIL</option><option>INSUFFICIENT_EVIDENCE</option><option>NOT_APPLICABLE</option></select><textarea name="exceptionSummary" placeholder="Exception summary if relevant"/><textarea name="conclusion" placeholder="Auditor conclusion"/><p className="lede compact">Conclusive PASS/FAIL is rejected unless the selected Evidence Gate is PASS.</p><button disabled={busy}>Record test result</button></form>
 </div></section>;
}
